name = "googology"
version = "0.6.176"
defaultTargets = ["Googology", "Test"]

[leanOptions]
pp.unicode.fun = true

[[lean_lib]]
name = "Googology"

[[lean_lib]]
name = "Test"
srcDir = "test"
globs = ["Test", "ExBuchholzCheck", "TransCheck", "YCheck", "GoalsAudit"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.30.0"

[[require]]
name = "bmselempattern"
git = "https://github.com/koteitan/bms-elem-pattern"
subDir = "lean"
rev = "main"

[[require]]
name = "pss"
git = "https://github.com/koteitan/pss-proof"
subDir = "lean"
rev = "main"
