name = "googology"
version = "0.1.6"
defaultTargets = ["Googology", "Test"]

[leanOptions]
pp.unicode.fun = true

[[lean_lib]]
name = "Googology"

[[lean_lib]]
name = "Test"
srcDir = "test"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.30.0"
