import Googology.Trans.BMS.TrioFixNonLastOther2
import Googology.Trans.BMS.TrioRulesNonLastSheet

/-!
# The patch `TrioFixNonLastOther2`: the pairs it puts back in order

`TrioFixNonLastOther2.lean` narrows Fix M, Fix G and change 1 of
`TrioFixNonLastOther.lean` (rules 1–10 of [koteitan/trio](https://github.com/koteitan/trio)
with Fixes A–E, N, G, M).  `x2Of` is this patch, `xOf` is `TrioFixNonLastOther`, `allOf`
is `TrioRulesAll` (before `TrioFixNonLastOther`).

* **The review's nine pairs**: in order under `allOf` and `x2Of`, out of order under
  `xOf`.
* **What stays**: the 27 BMS expansions `M(P+t·ω)[n] = M(P+t·(n+1))` (`n = 1, 2`) and
  change 4's `M(Ω_{Ω_ω}+Ω_Ω+Ω_{ω·2})[n] = M(Ω_{Ω_ω}+Ω_Ω+Ω_{ω+n+1})`; three calibrated
  families keep the counts of `TrioFixNonLastOtherSheet.lean` (the other two are in
  `TrioFixNonLastOther2SheetHeavy1.lean`).
* **Against `TrioRulesAll`**: eight families; `brokenFixed` counts the pairs in order
  under `allOf` and out of order under `x2Of` (0 after `Ω_{Ω_2}`, `Ω_{Ω_3}`, `Ω_{Ω_4}`,
  `Ω_{Ω+1}`, `Ω_{Ω_{Ω+1}}`, `Ω_{Ω_{ω·2}}`; 8 after `Ω_{Ω_{ω^2}}`, 6 after
  `Ω_{Ω_{ω+1}}`) and the other way round.  Four heavier families are in
  `TrioFixNonLastOther2SheetHeavy2.lean`.

Standardness (yaBMS `bms -s`) is checked outside Lean: no matrix that is standard under
`allOf` becomes non-standard under `x2Of` in these families.  All of it is `#guard`s: a
calibration, not a theorem.  About 140 seconds for a check.
-/

namespace Googology.Trans.BMS.TrioFixNonLastOther2

open Googology.Trans.BMS.TrioRules
open Googology.Trans.BMS.TrioRules2
open Googology.Trans.BMS.TrioRulesNL
open Googology.Trans.BMS.TrioRulesAll
open Googology.Trans.BMS.TrioFixNonLastOther
open Googology.Trans.BMS (expandRL)

/-- `ordPair a b`: the order of the labels `a`, `b` as ordinals. -/
def ordPair (a b : String) : Ordering := cmpOrd ((parse a).getD []) ((parse b).getD [])

/-! ## The regressions of `TrioFixNonLastOther` that the narrowing removes

For each pair `(a, b)`: `TrioRulesAll` (`allOf`, before `TrioFixNonLastOther`) puts the
matrices in the order of the ordinals, `TrioFixNonLastOther` (`xOf`) does not, and this
patch (`x2Of`) does. -/

/-- The pairs of the review: Fix M (`Ω_2`, `Ω_3`, `Ω_4`, `Ω+1`, `Ω_{Ω+1}`), Fix G
(`Ω_{ω·2}`, `Ω_{ω+2}`, `Ω_{Ω_ω}`) and change 1 (`Ω_{ω^2}`). -/
def reviewPairs : List (String × String) := [
  ("W_W_2+W_w+W", "W_W_2+W+w"),
  ("W_W_3+W_w+W", "W_W_3+W+w"),
  ("W_W_4+W_w+W", "W_W_4+W+w"),
  ("W_(W+1)+W_w+W", "W_(W+1)+W+w"),
  ("W_W_(W+1)+W_w+W", "W_W_(W+1)+W+w"),
  ("W_W_(w2)+W_(w2)", "W_W_(w2)+W_W+W"),
  ("W_W_(w+2)+W_W+W", "W_W_(w+2)+W_(w+1)+w"),
  ("W_W_W_w+W_W+W", "W_W_W_w+W_w+1"),
  ("W_W_(w^2)+W_(w2)", "W_W_(w^2)+W_w+W")]

#guard reviewPairs.length = 9
#guard reviewPairs.all fun (a, b) =>
  let o := ordPair a b
  cmpMat (x2Of a) (x2Of b) == o && cmpMat (xOf a) (xOf b) != o && cmpMat (allOf a) (allOf b) == o

/-! ## What the narrowing keeps

`M(P+t·ω)[n] = M(P+t·(n+1))` (`n = 1, 2`) on the 27 labels of
`TrioFixNonLastOtherSheet.lean`, and change 4's own copies, still hold. -/

/-- `(P + t·ω, P + t·2, P + t·3)`. -/
def fsLabels2 : List (String × String × String) := [
  ("W_W_w+W*w", "W_W_w+W*2", "W_W_w+W*3"),
  ("W_W_w+W_W_w+W*w", "W_W_w+W_W_w+W*2", "W_W_w+W_W_w+W*3"),
  ("W_W_w+W_W+W*w", "W_W_w+W_W+W*2", "W_W_w+W_W+W*3"),
  ("W_W_w+W_(w+1)+W*w", "W_W_w+W_(w+1)+W*2", "W_W_w+W_(w+1)+W*3"),
  ("W_W_w+W_w+W*w", "W_W_w+W_w+W*2", "W_W_w+W_w+W*3"),
  ("W_W_w+W_2+W*w", "W_W_w+W_2+W*2", "W_W_w+W_2+W*3"),
  ("W_W_w+W_W_w+W_W_w+W*w", "W_W_w+W_W_w+W_W_w+W*2", "W_W_w+W_W_w+W_W_w+W*3"),
  ("W_W_w+W_W_w+W_W+W*w", "W_W_w+W_W_w+W_W+W*2", "W_W_w+W_W_w+W_W+W*3"),
  ("W_W_w+W_W_w+W_(w+1)+W*w", "W_W_w+W_W_w+W_(w+1)+W*2", "W_W_w+W_W_w+W_(w+1)+W*3"),
  ("W_W_w+W_W_w+W_w+W*w", "W_W_w+W_W_w+W_w+W*2", "W_W_w+W_W_w+W_w+W*3"),
  ("W_W_w+W_W_w+W_2+W*w", "W_W_w+W_W_w+W_2+W*2", "W_W_w+W_W_w+W_2+W*3"),
  ("W_W_w+W_W+W_W+W*w", "W_W_w+W_W+W_W+W*2", "W_W_w+W_W+W_W+W*3"),
  ("W_W_w+W_W+W_(w+1)+W*w", "W_W_w+W_W+W_(w+1)+W*2", "W_W_w+W_W+W_(w+1)+W*3"),
  ("W_W_w+W_W+W_w+W*w", "W_W_w+W_W+W_w+W*2", "W_W_w+W_W+W_w+W*3"),
  ("W_W_w+W_W+W_2+W*w", "W_W_w+W_W+W_2+W*2", "W_W_w+W_W+W_2+W*3"),
  ("W_W_w+W_(w+1)+W_(w+1)+W*w", "W_W_w+W_(w+1)+W_(w+1)+W*2", "W_W_w+W_(w+1)+W_(w+1)+W*3"),
  ("W_W_w+W_(w+1)+W_w+W*w", "W_W_w+W_(w+1)+W_w+W*2", "W_W_w+W_(w+1)+W_w+W*3"),
  ("W_W_w+W_(w+1)+W_2+W*w", "W_W_w+W_(w+1)+W_2+W*2", "W_W_w+W_(w+1)+W_2+W*3"),
  ("W_W_w+W_w+W_w+W*w", "W_W_w+W_w+W_w+W*2", "W_W_w+W_w+W_w+W*3"),
  ("W_W_w+W_w+W_2+W*w", "W_W_w+W_w+W_2+W*2", "W_W_w+W_w+W_2+W*3"),
  ("W_W_w+W_2+W_2+W*w", "W_W_w+W_2+W_2+W*2", "W_W_w+W_2+W_2+W*3"),
  ("W_W_w+W_(w2)+W*w", "W_W_w+W_(w2)+W*2", "W_W_w+W_(w2)+W*3"),
  ("W_W_w+W_W_w+W_(w2)+W*w", "W_W_w+W_W_w+W_(w2)+W*2", "W_W_w+W_W_w+W_(w2)+W*3"),
  ("W_W_w+W_W+W_(w2)+W*w", "W_W_w+W_W+W_(w2)+W*2", "W_W_w+W_W+W_(w2)+W*3"),
  ("W_W_w+W_(w2)+W_(w2)+W*w", "W_W_w+W_(w2)+W_(w2)+W*2", "W_W_w+W_(w2)+W_(w2)+W*3"),
  ("W_W_w+W_(w2)+W_(w+1)+W*w", "W_W_w+W_(w2)+W_(w+1)+W*2", "W_W_w+W_(w2)+W_(w+1)+W*3"),
  ("W_W_w+W_(w2)+W_w+W*w", "W_W_w+W_(w2)+W_w+W*2", "W_W_w+W_(w2)+W_w+W*3")]

#guard fsLabels2.length = 27
#guard fsLabels2.all fun (l, a, b) =>
  let m := x2Of l
  expandRL 3 1 m = x2Of a && expandRL 3 2 m = x2Of b
#guard expandRL 3 1 (x2Of "W_W_w+W_W+W_(w2)") = x2Of "W_W_w+W_W+W_(w+2)"
#guard expandRL 3 2 (x2Of "W_W_w+W_W+W_(w2)") = x2Of "W_W_w+W_W+W_(w+3)"

/-! ## Three of the five calibrated families of `TrioFixNonLastOther`

Order disagreements and colliding pairs under this patch: the counts of
`TrioFixNonLastOtherSheet.lean` (after `Ω_{Ω_2}`, `Ω_{Ω_Ω}`, `Ω_Ω`: `0, 3, 1` and
`0, 2, 1`), unchanged.  The families after `Ω_{Ω_ω}` and `Ω_{Ω_{ω+1}}` are in the heavy
sheet `TrioFixNonLastOther2SheetHeavy1.lean`. -/

/-- Sums of up to three terms from `1, ω, Ω, Ω_2, Ω_3, Ω_4, Ω_{Ω_2}` after `Ω_{Ω_2}`, and products. -/
def famU22 : List String := [
  "W_W_2",
  "W_W_2+W_W_2",
  "W_W_2+W_4",
  "W_W_2+W_3",
  "W_W_2+W_2",
  "W_W_2+W",
  "W_W_2+w",
  "W_W_2+1",
  "W_W_2+W_W_2+W_W_2",
  "W_W_2+W_W_2+W_4",
  "W_W_2+W_W_2+W_3",
  "W_W_2+W_W_2+W_2",
  "W_W_2+W_W_2+W",
  "W_W_2+W_W_2+w",
  "W_W_2+W_W_2+1",
  "W_W_2+W_4+W_4",
  "W_W_2+W_4+W_3",
  "W_W_2+W_4+W_2",
  "W_W_2+W_4+W",
  "W_W_2+W_4+w",
  "W_W_2+W_4+1",
  "W_W_2+W_3+W_3",
  "W_W_2+W_3+W_2",
  "W_W_2+W_3+W",
  "W_W_2+W_3+w",
  "W_W_2+W_3+1",
  "W_W_2+W_2+W_2",
  "W_W_2+W_2+W",
  "W_W_2+W_2+w",
  "W_W_2+W_2+1",
  "W_W_2+W+W",
  "W_W_2+W+w",
  "W_W_2+W+1",
  "W_W_2+w+w",
  "W_W_2+w+1",
  "W_W_2+1+1",
  "W_W_2+W_W_2+W_W_2+W_W_2",
  "W_W_2+W_W_2+W_W_2+W_4",
  "W_W_2+W_W_2+W_W_2+W_3",
  "W_W_2+W_W_2+W_W_2+W_2",
  "W_W_2+W_W_2+W_W_2+W",
  "W_W_2+W_W_2+W_W_2+w",
  "W_W_2+W_W_2+W_W_2+1",
  "W_W_2+W_W_2+W_4+W_4",
  "W_W_2+W_W_2+W_4+W_3",
  "W_W_2+W_W_2+W_4+W_2",
  "W_W_2+W_W_2+W_4+W",
  "W_W_2+W_W_2+W_4+w",
  "W_W_2+W_W_2+W_4+1",
  "W_W_2+W_W_2+W_3+W_3",
  "W_W_2+W_W_2+W_3+W_2",
  "W_W_2+W_W_2+W_3+W",
  "W_W_2+W_W_2+W_3+w",
  "W_W_2+W_W_2+W_3+1",
  "W_W_2+W_W_2+W_2+W_2",
  "W_W_2+W_W_2+W_2+W",
  "W_W_2+W_W_2+W_2+w",
  "W_W_2+W_W_2+W_2+1",
  "W_W_2+W_W_2+W+W",
  "W_W_2+W_W_2+W+w",
  "W_W_2+W_W_2+W+1",
  "W_W_2+W_W_2+w+w",
  "W_W_2+W_W_2+w+1",
  "W_W_2+W_W_2+1+1",
  "W_W_2+W_4+W_4+W_4",
  "W_W_2+W_4+W_4+W_3",
  "W_W_2+W_4+W_4+W_2",
  "W_W_2+W_4+W_4+W",
  "W_W_2+W_4+W_4+w",
  "W_W_2+W_4+W_4+1",
  "W_W_2+W_4+W_3+W_3",
  "W_W_2+W_4+W_3+W_2",
  "W_W_2+W_4+W_3+W",
  "W_W_2+W_4+W_3+w",
  "W_W_2+W_4+W_3+1",
  "W_W_2+W_4+W_2+W_2",
  "W_W_2+W_4+W_2+W",
  "W_W_2+W_4+W_2+w",
  "W_W_2+W_4+W_2+1",
  "W_W_2+W_4+W+W",
  "W_W_2+W_4+W+w",
  "W_W_2+W_4+W+1",
  "W_W_2+W_4+w+w",
  "W_W_2+W_4+w+1",
  "W_W_2+W_4+1+1",
  "W_W_2+W_3+W_3+W_3",
  "W_W_2+W_3+W_3+W_2",
  "W_W_2+W_3+W_3+W",
  "W_W_2+W_3+W_3+w",
  "W_W_2+W_3+W_3+1",
  "W_W_2+W_3+W_2+W_2",
  "W_W_2+W_3+W_2+W",
  "W_W_2+W_3+W_2+w",
  "W_W_2+W_3+W_2+1",
  "W_W_2+W_3+W+W",
  "W_W_2+W_3+W+w",
  "W_W_2+W_3+W+1",
  "W_W_2+W_3+w+w",
  "W_W_2+W_3+w+1",
  "W_W_2+W_3+1+1",
  "W_W_2+W_2+W_2+W_2",
  "W_W_2+W_2+W_2+W",
  "W_W_2+W_2+W_2+w",
  "W_W_2+W_2+W_2+1",
  "W_W_2+W_2+W+W",
  "W_W_2+W_2+W+w",
  "W_W_2+W_2+W+1",
  "W_W_2+W_2+w+w",
  "W_W_2+W_2+w+1",
  "W_W_2+W_2+1+1",
  "W_W_2+W+W+W",
  "W_W_2+W+W+w",
  "W_W_2+W+W+1",
  "W_W_2+W+w+w",
  "W_W_2+W+w+1",
  "W_W_2+W+1+1",
  "W_W_2+w+w+w",
  "W_W_2+w+w+1",
  "W_W_2+w+1+1",
  "W_W_2+1+1+1",
  "W_W_2*w",
  "W_W_2*W",
  "W_W_2*W_2",
  "W_W_2^2"]

/-- Sums of up to three terms from `1, Ω, Ω_2, Ω_ω, Ω_Ω, Ω_{Ω+1}, Ω_{Ω_ω}, Ω_{Ω_Ω}` after `Ω_{Ω_Ω}`, and products. -/
def famUWm2 : List String := [
  "W_W_W",
  "W_W_W+W_W_W",
  "W_W_W+W_W_w",
  "W_W_W+W_(W+1)",
  "W_W_W+W_W",
  "W_W_W+W_w",
  "W_W_W+W_2",
  "W_W_W+W",
  "W_W_W+1",
  "W_W_W+W_W_W+W_W_W",
  "W_W_W+W_W_W+W_W_w",
  "W_W_W+W_W_W+W_(W+1)",
  "W_W_W+W_W_W+W_W",
  "W_W_W+W_W_W+W_w",
  "W_W_W+W_W_W+W_2",
  "W_W_W+W_W_W+W",
  "W_W_W+W_W_W+1",
  "W_W_W+W_W_w+W_W_w",
  "W_W_W+W_W_w+W_(W+1)",
  "W_W_W+W_W_w+W_W",
  "W_W_W+W_W_w+W_w",
  "W_W_W+W_W_w+W_2",
  "W_W_W+W_W_w+W",
  "W_W_W+W_W_w+1",
  "W_W_W+W_(W+1)+W_(W+1)",
  "W_W_W+W_(W+1)+W_W",
  "W_W_W+W_(W+1)+W_w",
  "W_W_W+W_(W+1)+W_2",
  "W_W_W+W_(W+1)+W",
  "W_W_W+W_(W+1)+1",
  "W_W_W+W_W+W_W",
  "W_W_W+W_W+W_w",
  "W_W_W+W_W+W_2",
  "W_W_W+W_W+W",
  "W_W_W+W_W+1",
  "W_W_W+W_w+W_w",
  "W_W_W+W_w+W_2",
  "W_W_W+W_w+W",
  "W_W_W+W_w+1",
  "W_W_W+W_2+W_2",
  "W_W_W+W_2+W",
  "W_W_W+W_2+1",
  "W_W_W+W+W",
  "W_W_W+W+1",
  "W_W_W+1+1",
  "W_W_W+W_W_W+W_W_W+W_W_W",
  "W_W_W+W_W_W+W_W_W+W_W_w",
  "W_W_W+W_W_W+W_W_W+W_(W+1)",
  "W_W_W+W_W_W+W_W_W+W_W",
  "W_W_W+W_W_W+W_W_W+W_w",
  "W_W_W+W_W_W+W_W_W+W_2",
  "W_W_W+W_W_W+W_W_W+W",
  "W_W_W+W_W_W+W_W_W+1",
  "W_W_W+W_W_W+W_W_w+W_W_w",
  "W_W_W+W_W_W+W_W_w+W_(W+1)",
  "W_W_W+W_W_W+W_W_w+W_W",
  "W_W_W+W_W_W+W_W_w+W_w",
  "W_W_W+W_W_W+W_W_w+W_2",
  "W_W_W+W_W_W+W_W_w+W",
  "W_W_W+W_W_W+W_W_w+1",
  "W_W_W+W_W_W+W_(W+1)+W_(W+1)",
  "W_W_W+W_W_W+W_(W+1)+W_W",
  "W_W_W+W_W_W+W_(W+1)+W_w",
  "W_W_W+W_W_W+W_(W+1)+W_2",
  "W_W_W+W_W_W+W_(W+1)+W",
  "W_W_W+W_W_W+W_(W+1)+1",
  "W_W_W+W_W_W+W_W+W_W",
  "W_W_W+W_W_W+W_W+W_w",
  "W_W_W+W_W_W+W_W+W_2",
  "W_W_W+W_W_W+W_W+W",
  "W_W_W+W_W_W+W_W+1",
  "W_W_W+W_W_W+W_w+W_w",
  "W_W_W+W_W_W+W_w+W_2",
  "W_W_W+W_W_W+W_w+W",
  "W_W_W+W_W_W+W_w+1",
  "W_W_W+W_W_W+W_2+W_2",
  "W_W_W+W_W_W+W_2+W",
  "W_W_W+W_W_W+W_2+1",
  "W_W_W+W_W_W+W+W",
  "W_W_W+W_W_W+W+1",
  "W_W_W+W_W_W+1+1",
  "W_W_W+W_W_w+W_W_w+W_W_w",
  "W_W_W+W_W_w+W_W_w+W_(W+1)",
  "W_W_W+W_W_w+W_W_w+W_W",
  "W_W_W+W_W_w+W_W_w+W_w",
  "W_W_W+W_W_w+W_W_w+W_2",
  "W_W_W+W_W_w+W_W_w+W",
  "W_W_W+W_W_w+W_W_w+1",
  "W_W_W+W_W_w+W_(W+1)+W_(W+1)",
  "W_W_W+W_W_w+W_(W+1)+W_W",
  "W_W_W+W_W_w+W_(W+1)+W_w",
  "W_W_W+W_W_w+W_(W+1)+W_2",
  "W_W_W+W_W_w+W_(W+1)+W",
  "W_W_W+W_W_w+W_(W+1)+1",
  "W_W_W+W_W_w+W_W+W_W",
  "W_W_W+W_W_w+W_W+W_w",
  "W_W_W+W_W_w+W_W+W_2",
  "W_W_W+W_W_w+W_W+W",
  "W_W_W+W_W_w+W_W+1",
  "W_W_W+W_W_w+W_w+W_w",
  "W_W_W+W_W_w+W_w+W_2",
  "W_W_W+W_W_w+W_w+W",
  "W_W_W+W_W_w+W_w+1",
  "W_W_W+W_W_w+W_2+W_2",
  "W_W_W+W_W_w+W_2+W",
  "W_W_W+W_W_w+W_2+1",
  "W_W_W+W_W_w+W+W",
  "W_W_W+W_W_w+W+1",
  "W_W_W+W_W_w+1+1",
  "W_W_W+W_(W+1)+W_(W+1)+W_(W+1)",
  "W_W_W+W_(W+1)+W_(W+1)+W_W",
  "W_W_W+W_(W+1)+W_(W+1)+W_w",
  "W_W_W+W_(W+1)+W_(W+1)+W_2",
  "W_W_W+W_(W+1)+W_(W+1)+W",
  "W_W_W+W_(W+1)+W_(W+1)+1",
  "W_W_W+W_(W+1)+W_W+W_W",
  "W_W_W+W_(W+1)+W_W+W_w",
  "W_W_W+W_(W+1)+W_W+W_2",
  "W_W_W+W_(W+1)+W_W+W",
  "W_W_W+W_(W+1)+W_W+1",
  "W_W_W+W_(W+1)+W_w+W_w",
  "W_W_W+W_(W+1)+W_w+W_2",
  "W_W_W+W_(W+1)+W_w+W",
  "W_W_W+W_(W+1)+W_w+1",
  "W_W_W+W_(W+1)+W_2+W_2",
  "W_W_W+W_(W+1)+W_2+W",
  "W_W_W+W_(W+1)+W_2+1",
  "W_W_W+W_(W+1)+W+W",
  "W_W_W+W_(W+1)+W+1",
  "W_W_W+W_(W+1)+1+1",
  "W_W_W+W_W+W_W+W_W",
  "W_W_W+W_W+W_W+W_w",
  "W_W_W+W_W+W_W+W_2",
  "W_W_W+W_W+W_W+W",
  "W_W_W+W_W+W_W+1",
  "W_W_W+W_W+W_w+W_w",
  "W_W_W+W_W+W_w+W_2",
  "W_W_W+W_W+W_w+W",
  "W_W_W+W_W+W_w+1",
  "W_W_W+W_W+W_2+W_2",
  "W_W_W+W_W+W_2+W",
  "W_W_W+W_W+W_2+1",
  "W_W_W+W_W+W+W",
  "W_W_W+W_W+W+1",
  "W_W_W+W_W+1+1",
  "W_W_W+W_w+W_w+W_w",
  "W_W_W+W_w+W_w+W_2",
  "W_W_W+W_w+W_w+W",
  "W_W_W+W_w+W_w+1",
  "W_W_W+W_w+W_2+W_2",
  "W_W_W+W_w+W_2+W",
  "W_W_W+W_w+W_2+1",
  "W_W_W+W_w+W+W",
  "W_W_W+W_w+W+1",
  "W_W_W+W_w+1+1",
  "W_W_W+W_2+W_2+W_2",
  "W_W_W+W_2+W_2+W",
  "W_W_W+W_2+W_2+1",
  "W_W_W+W_2+W+W",
  "W_W_W+W_2+W+1",
  "W_W_W+W_2+1+1",
  "W_W_W+W+W+W",
  "W_W_W+W+W+1",
  "W_W_W+W+1+1",
  "W_W_W+1+1+1",
  "W_W_W*w",
  "W_W_W*W_w",
  "W_W_W*W_W_w"]

/-- Sums of up to three terms from `1, Ω, Ω_2, Ω_ω, Ω_Ω` after `Ω_Ω`, and products. -/
def famU1m2 : List String := [
  "W_W",
  "W_W+W_W",
  "W_W+W_w",
  "W_W+W_2",
  "W_W+W",
  "W_W+1",
  "W_W+W_W+W_W",
  "W_W+W_W+W_w",
  "W_W+W_W+W_2",
  "W_W+W_W+W",
  "W_W+W_W+1",
  "W_W+W_w+W_w",
  "W_W+W_w+W_2",
  "W_W+W_w+W",
  "W_W+W_w+1",
  "W_W+W_2+W_2",
  "W_W+W_2+W",
  "W_W+W_2+1",
  "W_W+W+W",
  "W_W+W+1",
  "W_W+1+1",
  "W_W+W_W+W_W+W_W",
  "W_W+W_W+W_W+W_w",
  "W_W+W_W+W_W+W_2",
  "W_W+W_W+W_W+W",
  "W_W+W_W+W_W+1",
  "W_W+W_W+W_w+W_w",
  "W_W+W_W+W_w+W_2",
  "W_W+W_W+W_w+W",
  "W_W+W_W+W_w+1",
  "W_W+W_W+W_2+W_2",
  "W_W+W_W+W_2+W",
  "W_W+W_W+W_2+1",
  "W_W+W_W+W+W",
  "W_W+W_W+W+1",
  "W_W+W_W+1+1",
  "W_W+W_w+W_w+W_w",
  "W_W+W_w+W_w+W_2",
  "W_W+W_w+W_w+W",
  "W_W+W_w+W_w+1",
  "W_W+W_w+W_2+W_2",
  "W_W+W_w+W_2+W",
  "W_W+W_w+W_2+1",
  "W_W+W_w+W+W",
  "W_W+W_w+W+1",
  "W_W+W_w+1+1",
  "W_W+W_2+W_2+W_2",
  "W_W+W_2+W_2+W",
  "W_W+W_2+W_2+1",
  "W_W+W_2+W+W",
  "W_W+W_2+W+1",
  "W_W+W_2+1+1",
  "W_W+W+W+W",
  "W_W+W+W+1",
  "W_W+W+1+1",
  "W_W+1+1+1",
  "W_W*w",
  "W_W*W_w"]

#guard (famU22.length, famUWm2.length, famU1m2.length) = (124, 168, 58)
#guard (let xs := withM x2Of famU22; (pairDisagreements xs, collisions xs)) = (0, 0)
#guard (let xs := withM x2Of famUWm2; (pairDisagreements xs, collisions xs)) = (3, 2)
#guard (let xs := withM x2Of famU1m2; (pairDisagreements xs, collisions xs)) = (1, 1)

/-! ## Against `TrioRulesAll` on the families of the review and nearby

`brokenFixed xs ys = (b, f)`: `b` pairs are in the order of the ordinals under `ys`
(`TrioRulesAll`) and not under `xs` (this patch), `f` the other way round.  Each guard is
`(disagreements, colliding pairs)` of this patch, the same of `TrioRulesAll`, and
`brokenFixed`. -/

/-- `(broken, fixed)` of `xs` against `ys` (same labels, same order). -/
def brokenFixed (xs ys : Array (Od × List (List Nat))) : Nat × Nat := Id.run do
  let mut b := 0
  let mut f := 0
  for i in [0:xs.size] do
    for j in [i+1:xs.size] do
      let o := cmpOrd xs[i]!.1 xs[j]!.1
      let okx := cmpMat xs[i]!.2 xs[j]!.2 == o
      let oky := cmpMat ys[i]!.2 ys[j]!.2 == o
      if oky && !okx then b := b + 1
      if okx && !oky then f := f + 1
  return (b, f)

/-- The five counts of a family: this patch, `TrioRulesAll`, `brokenFixed`. -/
def famCounts (ls : List String) : Nat × Nat × Nat × Nat × (Nat × Nat) :=
  let xs := withM x2Of ls
  let ys := withM allOf ls
  (pairDisagreements xs, collisions xs, pairDisagreements ys, collisions ys, brokenFixed xs ys)

/-- Sums of up to three terms after `Ω_{Ω_2}` from `1, ω, Ω, Ω_2, Ω_3, Ω_4, Ω_ω, Ω_{Ω_2}` (Fix M; `TrioFixNonLastOther` breaks 278), and products. -/
def famRW2 : List String := [
  "W_W_2",
  "W_W_2+W_W_2",
  "W_W_2+W_w",
  "W_W_2+W_4",
  "W_W_2+W_3",
  "W_W_2+W_2",
  "W_W_2+W",
  "W_W_2+w",
  "W_W_2+1",
  "W_W_2+W_W_2+W_W_2",
  "W_W_2+W_W_2+W_w",
  "W_W_2+W_W_2+W_4",
  "W_W_2+W_W_2+W_3",
  "W_W_2+W_W_2+W_2",
  "W_W_2+W_W_2+W",
  "W_W_2+W_W_2+w",
  "W_W_2+W_W_2+1",
  "W_W_2+W_w+W_w",
  "W_W_2+W_w+W_4",
  "W_W_2+W_w+W_3",
  "W_W_2+W_w+W_2",
  "W_W_2+W_w+W",
  "W_W_2+W_w+w",
  "W_W_2+W_w+1",
  "W_W_2+W_4+W_4",
  "W_W_2+W_4+W_3",
  "W_W_2+W_4+W_2",
  "W_W_2+W_4+W",
  "W_W_2+W_4+w",
  "W_W_2+W_4+1",
  "W_W_2+W_3+W_3",
  "W_W_2+W_3+W_2",
  "W_W_2+W_3+W",
  "W_W_2+W_3+w",
  "W_W_2+W_3+1",
  "W_W_2+W_2+W_2",
  "W_W_2+W_2+W",
  "W_W_2+W_2+w",
  "W_W_2+W_2+1",
  "W_W_2+W+W",
  "W_W_2+W+w",
  "W_W_2+W+1",
  "W_W_2+w+w",
  "W_W_2+w+1",
  "W_W_2+1+1",
  "W_W_2+W_W_2+W_W_2+W_W_2",
  "W_W_2+W_W_2+W_W_2+W_w",
  "W_W_2+W_W_2+W_W_2+W_4",
  "W_W_2+W_W_2+W_W_2+W_3",
  "W_W_2+W_W_2+W_W_2+W_2",
  "W_W_2+W_W_2+W_W_2+W",
  "W_W_2+W_W_2+W_W_2+w",
  "W_W_2+W_W_2+W_W_2+1",
  "W_W_2+W_W_2+W_w+W_w",
  "W_W_2+W_W_2+W_w+W_4",
  "W_W_2+W_W_2+W_w+W_3",
  "W_W_2+W_W_2+W_w+W_2",
  "W_W_2+W_W_2+W_w+W",
  "W_W_2+W_W_2+W_w+w",
  "W_W_2+W_W_2+W_w+1",
  "W_W_2+W_W_2+W_4+W_4",
  "W_W_2+W_W_2+W_4+W_3",
  "W_W_2+W_W_2+W_4+W_2",
  "W_W_2+W_W_2+W_4+W",
  "W_W_2+W_W_2+W_4+w",
  "W_W_2+W_W_2+W_4+1",
  "W_W_2+W_W_2+W_3+W_3",
  "W_W_2+W_W_2+W_3+W_2",
  "W_W_2+W_W_2+W_3+W",
  "W_W_2+W_W_2+W_3+w",
  "W_W_2+W_W_2+W_3+1",
  "W_W_2+W_W_2+W_2+W_2",
  "W_W_2+W_W_2+W_2+W",
  "W_W_2+W_W_2+W_2+w",
  "W_W_2+W_W_2+W_2+1",
  "W_W_2+W_W_2+W+W",
  "W_W_2+W_W_2+W+w",
  "W_W_2+W_W_2+W+1",
  "W_W_2+W_W_2+w+w",
  "W_W_2+W_W_2+w+1",
  "W_W_2+W_W_2+1+1",
  "W_W_2+W_w+W_w+W_w",
  "W_W_2+W_w+W_w+W_4",
  "W_W_2+W_w+W_w+W_3",
  "W_W_2+W_w+W_w+W_2",
  "W_W_2+W_w+W_w+W",
  "W_W_2+W_w+W_w+w",
  "W_W_2+W_w+W_w+1",
  "W_W_2+W_w+W_4+W_4",
  "W_W_2+W_w+W_4+W_3",
  "W_W_2+W_w+W_4+W_2",
  "W_W_2+W_w+W_4+W",
  "W_W_2+W_w+W_4+w",
  "W_W_2+W_w+W_4+1",
  "W_W_2+W_w+W_3+W_3",
  "W_W_2+W_w+W_3+W_2",
  "W_W_2+W_w+W_3+W",
  "W_W_2+W_w+W_3+w",
  "W_W_2+W_w+W_3+1",
  "W_W_2+W_w+W_2+W_2",
  "W_W_2+W_w+W_2+W",
  "W_W_2+W_w+W_2+w",
  "W_W_2+W_w+W_2+1",
  "W_W_2+W_w+W+W",
  "W_W_2+W_w+W+w",
  "W_W_2+W_w+W+1",
  "W_W_2+W_w+w+w",
  "W_W_2+W_w+w+1",
  "W_W_2+W_w+1+1",
  "W_W_2+W_4+W_4+W_4",
  "W_W_2+W_4+W_4+W_3",
  "W_W_2+W_4+W_4+W_2",
  "W_W_2+W_4+W_4+W",
  "W_W_2+W_4+W_4+w",
  "W_W_2+W_4+W_4+1",
  "W_W_2+W_4+W_3+W_3",
  "W_W_2+W_4+W_3+W_2",
  "W_W_2+W_4+W_3+W",
  "W_W_2+W_4+W_3+w",
  "W_W_2+W_4+W_3+1",
  "W_W_2+W_4+W_2+W_2",
  "W_W_2+W_4+W_2+W",
  "W_W_2+W_4+W_2+w",
  "W_W_2+W_4+W_2+1",
  "W_W_2+W_4+W+W",
  "W_W_2+W_4+W+w",
  "W_W_2+W_4+W+1",
  "W_W_2+W_4+w+w",
  "W_W_2+W_4+w+1",
  "W_W_2+W_4+1+1",
  "W_W_2+W_3+W_3+W_3",
  "W_W_2+W_3+W_3+W_2",
  "W_W_2+W_3+W_3+W",
  "W_W_2+W_3+W_3+w",
  "W_W_2+W_3+W_3+1",
  "W_W_2+W_3+W_2+W_2",
  "W_W_2+W_3+W_2+W",
  "W_W_2+W_3+W_2+w",
  "W_W_2+W_3+W_2+1",
  "W_W_2+W_3+W+W",
  "W_W_2+W_3+W+w",
  "W_W_2+W_3+W+1",
  "W_W_2+W_3+w+w",
  "W_W_2+W_3+w+1",
  "W_W_2+W_3+1+1",
  "W_W_2+W_2+W_2+W_2",
  "W_W_2+W_2+W_2+W",
  "W_W_2+W_2+W_2+w",
  "W_W_2+W_2+W_2+1",
  "W_W_2+W_2+W+W",
  "W_W_2+W_2+W+w",
  "W_W_2+W_2+W+1",
  "W_W_2+W_2+w+w",
  "W_W_2+W_2+w+1",
  "W_W_2+W_2+1+1",
  "W_W_2+W+W+W",
  "W_W_2+W+W+w",
  "W_W_2+W+W+1",
  "W_W_2+W+w+w",
  "W_W_2+W+w+1",
  "W_W_2+W+1+1",
  "W_W_2+w+w+w",
  "W_W_2+w+w+1",
  "W_W_2+w+1+1",
  "W_W_2+1+1+1",
  "W_W_2*w",
  "W_W_2*W_w"]

#guard famRW2.length = 167
#guard famCounts famRW2 = (2682, 18, 4377, 51, (0, 1695))

/-- Sums of up to three terms after `Ω_{Ω_3}` from `1, ω, Ω, Ω_2, Ω_3, Ω_4, Ω_ω, Ω_{Ω_3}` (Fix M; `TrioFixNonLastOther` breaks 276), and products. -/
def famRW3 : List String := [
  "W_W_3",
  "W_W_3+W_W_3",
  "W_W_3+W_w",
  "W_W_3+W_4",
  "W_W_3+W_3",
  "W_W_3+W_2",
  "W_W_3+W",
  "W_W_3+w",
  "W_W_3+1",
  "W_W_3+W_W_3+W_W_3",
  "W_W_3+W_W_3+W_w",
  "W_W_3+W_W_3+W_4",
  "W_W_3+W_W_3+W_3",
  "W_W_3+W_W_3+W_2",
  "W_W_3+W_W_3+W",
  "W_W_3+W_W_3+w",
  "W_W_3+W_W_3+1",
  "W_W_3+W_w+W_w",
  "W_W_3+W_w+W_4",
  "W_W_3+W_w+W_3",
  "W_W_3+W_w+W_2",
  "W_W_3+W_w+W",
  "W_W_3+W_w+w",
  "W_W_3+W_w+1",
  "W_W_3+W_4+W_4",
  "W_W_3+W_4+W_3",
  "W_W_3+W_4+W_2",
  "W_W_3+W_4+W",
  "W_W_3+W_4+w",
  "W_W_3+W_4+1",
  "W_W_3+W_3+W_3",
  "W_W_3+W_3+W_2",
  "W_W_3+W_3+W",
  "W_W_3+W_3+w",
  "W_W_3+W_3+1",
  "W_W_3+W_2+W_2",
  "W_W_3+W_2+W",
  "W_W_3+W_2+w",
  "W_W_3+W_2+1",
  "W_W_3+W+W",
  "W_W_3+W+w",
  "W_W_3+W+1",
  "W_W_3+w+w",
  "W_W_3+w+1",
  "W_W_3+1+1",
  "W_W_3+W_W_3+W_W_3+W_W_3",
  "W_W_3+W_W_3+W_W_3+W_w",
  "W_W_3+W_W_3+W_W_3+W_4",
  "W_W_3+W_W_3+W_W_3+W_3",
  "W_W_3+W_W_3+W_W_3+W_2",
  "W_W_3+W_W_3+W_W_3+W",
  "W_W_3+W_W_3+W_W_3+w",
  "W_W_3+W_W_3+W_W_3+1",
  "W_W_3+W_W_3+W_w+W_w",
  "W_W_3+W_W_3+W_w+W_4",
  "W_W_3+W_W_3+W_w+W_3",
  "W_W_3+W_W_3+W_w+W_2",
  "W_W_3+W_W_3+W_w+W",
  "W_W_3+W_W_3+W_w+w",
  "W_W_3+W_W_3+W_w+1",
  "W_W_3+W_W_3+W_4+W_4",
  "W_W_3+W_W_3+W_4+W_3",
  "W_W_3+W_W_3+W_4+W_2",
  "W_W_3+W_W_3+W_4+W",
  "W_W_3+W_W_3+W_4+w",
  "W_W_3+W_W_3+W_4+1",
  "W_W_3+W_W_3+W_3+W_3",
  "W_W_3+W_W_3+W_3+W_2",
  "W_W_3+W_W_3+W_3+W",
  "W_W_3+W_W_3+W_3+w",
  "W_W_3+W_W_3+W_3+1",
  "W_W_3+W_W_3+W_2+W_2",
  "W_W_3+W_W_3+W_2+W",
  "W_W_3+W_W_3+W_2+w",
  "W_W_3+W_W_3+W_2+1",
  "W_W_3+W_W_3+W+W",
  "W_W_3+W_W_3+W+w",
  "W_W_3+W_W_3+W+1",
  "W_W_3+W_W_3+w+w",
  "W_W_3+W_W_3+w+1",
  "W_W_3+W_W_3+1+1",
  "W_W_3+W_w+W_w+W_w",
  "W_W_3+W_w+W_w+W_4",
  "W_W_3+W_w+W_w+W_3",
  "W_W_3+W_w+W_w+W_2",
  "W_W_3+W_w+W_w+W",
  "W_W_3+W_w+W_w+w",
  "W_W_3+W_w+W_w+1",
  "W_W_3+W_w+W_4+W_4",
  "W_W_3+W_w+W_4+W_3",
  "W_W_3+W_w+W_4+W_2",
  "W_W_3+W_w+W_4+W",
  "W_W_3+W_w+W_4+w",
  "W_W_3+W_w+W_4+1",
  "W_W_3+W_w+W_3+W_3",
  "W_W_3+W_w+W_3+W_2",
  "W_W_3+W_w+W_3+W",
  "W_W_3+W_w+W_3+w",
  "W_W_3+W_w+W_3+1",
  "W_W_3+W_w+W_2+W_2",
  "W_W_3+W_w+W_2+W",
  "W_W_3+W_w+W_2+w",
  "W_W_3+W_w+W_2+1",
  "W_W_3+W_w+W+W",
  "W_W_3+W_w+W+w",
  "W_W_3+W_w+W+1",
  "W_W_3+W_w+w+w",
  "W_W_3+W_w+w+1",
  "W_W_3+W_w+1+1",
  "W_W_3+W_4+W_4+W_4",
  "W_W_3+W_4+W_4+W_3",
  "W_W_3+W_4+W_4+W_2",
  "W_W_3+W_4+W_4+W",
  "W_W_3+W_4+W_4+w",
  "W_W_3+W_4+W_4+1",
  "W_W_3+W_4+W_3+W_3",
  "W_W_3+W_4+W_3+W_2",
  "W_W_3+W_4+W_3+W",
  "W_W_3+W_4+W_3+w",
  "W_W_3+W_4+W_3+1",
  "W_W_3+W_4+W_2+W_2",
  "W_W_3+W_4+W_2+W",
  "W_W_3+W_4+W_2+w",
  "W_W_3+W_4+W_2+1",
  "W_W_3+W_4+W+W",
  "W_W_3+W_4+W+w",
  "W_W_3+W_4+W+1",
  "W_W_3+W_4+w+w",
  "W_W_3+W_4+w+1",
  "W_W_3+W_4+1+1",
  "W_W_3+W_3+W_3+W_3",
  "W_W_3+W_3+W_3+W_2",
  "W_W_3+W_3+W_3+W",
  "W_W_3+W_3+W_3+w",
  "W_W_3+W_3+W_3+1",
  "W_W_3+W_3+W_2+W_2",
  "W_W_3+W_3+W_2+W",
  "W_W_3+W_3+W_2+w",
  "W_W_3+W_3+W_2+1",
  "W_W_3+W_3+W+W",
  "W_W_3+W_3+W+w",
  "W_W_3+W_3+W+1",
  "W_W_3+W_3+w+w",
  "W_W_3+W_3+w+1",
  "W_W_3+W_3+1+1",
  "W_W_3+W_2+W_2+W_2",
  "W_W_3+W_2+W_2+W",
  "W_W_3+W_2+W_2+w",
  "W_W_3+W_2+W_2+1",
  "W_W_3+W_2+W+W",
  "W_W_3+W_2+W+w",
  "W_W_3+W_2+W+1",
  "W_W_3+W_2+w+w",
  "W_W_3+W_2+w+1",
  "W_W_3+W_2+1+1",
  "W_W_3+W+W+W",
  "W_W_3+W+W+w",
  "W_W_3+W+W+1",
  "W_W_3+W+w+w",
  "W_W_3+W+w+1",
  "W_W_3+W+1+1",
  "W_W_3+w+w+w",
  "W_W_3+w+w+1",
  "W_W_3+w+1+1",
  "W_W_3+1+1+1",
  "W_W_3*w",
  "W_W_3*W_w"]

#guard famRW3.length = 167
#guard famCounts famRW3 = (2682, 18, 3300, 60, (0, 618))

/-- Sums of up to three terms after `Ω_{Ω_4}` from `1, ω, Ω, Ω_2, Ω_3, Ω_4, Ω_ω, Ω_{Ω_4}` (Fix M; `TrioFixNonLastOther` breaks 276), and products. -/
def famRW4 : List String := [
  "W_W_4",
  "W_W_4+W_W_4",
  "W_W_4+W_w",
  "W_W_4+W_4",
  "W_W_4+W_3",
  "W_W_4+W_2",
  "W_W_4+W",
  "W_W_4+w",
  "W_W_4+1",
  "W_W_4+W_W_4+W_W_4",
  "W_W_4+W_W_4+W_w",
  "W_W_4+W_W_4+W_4",
  "W_W_4+W_W_4+W_3",
  "W_W_4+W_W_4+W_2",
  "W_W_4+W_W_4+W",
  "W_W_4+W_W_4+w",
  "W_W_4+W_W_4+1",
  "W_W_4+W_w+W_w",
  "W_W_4+W_w+W_4",
  "W_W_4+W_w+W_3",
  "W_W_4+W_w+W_2",
  "W_W_4+W_w+W",
  "W_W_4+W_w+w",
  "W_W_4+W_w+1",
  "W_W_4+W_4+W_4",
  "W_W_4+W_4+W_3",
  "W_W_4+W_4+W_2",
  "W_W_4+W_4+W",
  "W_W_4+W_4+w",
  "W_W_4+W_4+1",
  "W_W_4+W_3+W_3",
  "W_W_4+W_3+W_2",
  "W_W_4+W_3+W",
  "W_W_4+W_3+w",
  "W_W_4+W_3+1",
  "W_W_4+W_2+W_2",
  "W_W_4+W_2+W",
  "W_W_4+W_2+w",
  "W_W_4+W_2+1",
  "W_W_4+W+W",
  "W_W_4+W+w",
  "W_W_4+W+1",
  "W_W_4+w+w",
  "W_W_4+w+1",
  "W_W_4+1+1",
  "W_W_4+W_W_4+W_W_4+W_W_4",
  "W_W_4+W_W_4+W_W_4+W_w",
  "W_W_4+W_W_4+W_W_4+W_4",
  "W_W_4+W_W_4+W_W_4+W_3",
  "W_W_4+W_W_4+W_W_4+W_2",
  "W_W_4+W_W_4+W_W_4+W",
  "W_W_4+W_W_4+W_W_4+w",
  "W_W_4+W_W_4+W_W_4+1",
  "W_W_4+W_W_4+W_w+W_w",
  "W_W_4+W_W_4+W_w+W_4",
  "W_W_4+W_W_4+W_w+W_3",
  "W_W_4+W_W_4+W_w+W_2",
  "W_W_4+W_W_4+W_w+W",
  "W_W_4+W_W_4+W_w+w",
  "W_W_4+W_W_4+W_w+1",
  "W_W_4+W_W_4+W_4+W_4",
  "W_W_4+W_W_4+W_4+W_3",
  "W_W_4+W_W_4+W_4+W_2",
  "W_W_4+W_W_4+W_4+W",
  "W_W_4+W_W_4+W_4+w",
  "W_W_4+W_W_4+W_4+1",
  "W_W_4+W_W_4+W_3+W_3",
  "W_W_4+W_W_4+W_3+W_2",
  "W_W_4+W_W_4+W_3+W",
  "W_W_4+W_W_4+W_3+w",
  "W_W_4+W_W_4+W_3+1",
  "W_W_4+W_W_4+W_2+W_2",
  "W_W_4+W_W_4+W_2+W",
  "W_W_4+W_W_4+W_2+w",
  "W_W_4+W_W_4+W_2+1",
  "W_W_4+W_W_4+W+W",
  "W_W_4+W_W_4+W+w",
  "W_W_4+W_W_4+W+1",
  "W_W_4+W_W_4+w+w",
  "W_W_4+W_W_4+w+1",
  "W_W_4+W_W_4+1+1",
  "W_W_4+W_w+W_w+W_w",
  "W_W_4+W_w+W_w+W_4",
  "W_W_4+W_w+W_w+W_3",
  "W_W_4+W_w+W_w+W_2",
  "W_W_4+W_w+W_w+W",
  "W_W_4+W_w+W_w+w",
  "W_W_4+W_w+W_w+1",
  "W_W_4+W_w+W_4+W_4",
  "W_W_4+W_w+W_4+W_3",
  "W_W_4+W_w+W_4+W_2",
  "W_W_4+W_w+W_4+W",
  "W_W_4+W_w+W_4+w",
  "W_W_4+W_w+W_4+1",
  "W_W_4+W_w+W_3+W_3",
  "W_W_4+W_w+W_3+W_2",
  "W_W_4+W_w+W_3+W",
  "W_W_4+W_w+W_3+w",
  "W_W_4+W_w+W_3+1",
  "W_W_4+W_w+W_2+W_2",
  "W_W_4+W_w+W_2+W",
  "W_W_4+W_w+W_2+w",
  "W_W_4+W_w+W_2+1",
  "W_W_4+W_w+W+W",
  "W_W_4+W_w+W+w",
  "W_W_4+W_w+W+1",
  "W_W_4+W_w+w+w",
  "W_W_4+W_w+w+1",
  "W_W_4+W_w+1+1",
  "W_W_4+W_4+W_4+W_4",
  "W_W_4+W_4+W_4+W_3",
  "W_W_4+W_4+W_4+W_2",
  "W_W_4+W_4+W_4+W",
  "W_W_4+W_4+W_4+w",
  "W_W_4+W_4+W_4+1",
  "W_W_4+W_4+W_3+W_3",
  "W_W_4+W_4+W_3+W_2",
  "W_W_4+W_4+W_3+W",
  "W_W_4+W_4+W_3+w",
  "W_W_4+W_4+W_3+1",
  "W_W_4+W_4+W_2+W_2",
  "W_W_4+W_4+W_2+W",
  "W_W_4+W_4+W_2+w",
  "W_W_4+W_4+W_2+1",
  "W_W_4+W_4+W+W",
  "W_W_4+W_4+W+w",
  "W_W_4+W_4+W+1",
  "W_W_4+W_4+w+w",
  "W_W_4+W_4+w+1",
  "W_W_4+W_4+1+1",
  "W_W_4+W_3+W_3+W_3",
  "W_W_4+W_3+W_3+W_2",
  "W_W_4+W_3+W_3+W",
  "W_W_4+W_3+W_3+w",
  "W_W_4+W_3+W_3+1",
  "W_W_4+W_3+W_2+W_2",
  "W_W_4+W_3+W_2+W",
  "W_W_4+W_3+W_2+w",
  "W_W_4+W_3+W_2+1",
  "W_W_4+W_3+W+W",
  "W_W_4+W_3+W+w",
  "W_W_4+W_3+W+1",
  "W_W_4+W_3+w+w",
  "W_W_4+W_3+w+1",
  "W_W_4+W_3+1+1",
  "W_W_4+W_2+W_2+W_2",
  "W_W_4+W_2+W_2+W",
  "W_W_4+W_2+W_2+w",
  "W_W_4+W_2+W_2+1",
  "W_W_4+W_2+W+W",
  "W_W_4+W_2+W+w",
  "W_W_4+W_2+W+1",
  "W_W_4+W_2+w+w",
  "W_W_4+W_2+w+1",
  "W_W_4+W_2+1+1",
  "W_W_4+W+W+W",
  "W_W_4+W+W+w",
  "W_W_4+W+W+1",
  "W_W_4+W+w+w",
  "W_W_4+W+w+1",
  "W_W_4+W+1+1",
  "W_W_4+w+w+w",
  "W_W_4+w+w+1",
  "W_W_4+w+1+1",
  "W_W_4+1+1+1",
  "W_W_4*w",
  "W_W_4*W_w"]

#guard famRW4.length = 167
#guard famCounts famRW4 = (2682, 18, 2682, 18, (0, 0))

/-- Sums of up to three terms after `Ω_{Ω+1}` from `1, ω, Ω, Ω_2, Ω_ω, Ω_Ω, Ω_{Ω+1}` (Fix M; `TrioFixNonLastOther` breaks 144), and products. -/
def famRWp1 : List String := [
  "W_(W+1)",
  "W_(W+1)+W_(W+1)",
  "W_(W+1)+W_W",
  "W_(W+1)+W_w",
  "W_(W+1)+W_2",
  "W_(W+1)+W",
  "W_(W+1)+w",
  "W_(W+1)+1",
  "W_(W+1)+W_(W+1)+W_(W+1)",
  "W_(W+1)+W_(W+1)+W_W",
  "W_(W+1)+W_(W+1)+W_w",
  "W_(W+1)+W_(W+1)+W_2",
  "W_(W+1)+W_(W+1)+W",
  "W_(W+1)+W_(W+1)+w",
  "W_(W+1)+W_(W+1)+1",
  "W_(W+1)+W_W+W_W",
  "W_(W+1)+W_W+W_w",
  "W_(W+1)+W_W+W_2",
  "W_(W+1)+W_W+W",
  "W_(W+1)+W_W+w",
  "W_(W+1)+W_W+1",
  "W_(W+1)+W_w+W_w",
  "W_(W+1)+W_w+W_2",
  "W_(W+1)+W_w+W",
  "W_(W+1)+W_w+w",
  "W_(W+1)+W_w+1",
  "W_(W+1)+W_2+W_2",
  "W_(W+1)+W_2+W",
  "W_(W+1)+W_2+w",
  "W_(W+1)+W_2+1",
  "W_(W+1)+W+W",
  "W_(W+1)+W+w",
  "W_(W+1)+W+1",
  "W_(W+1)+w+w",
  "W_(W+1)+w+1",
  "W_(W+1)+1+1",
  "W_(W+1)+W_(W+1)+W_(W+1)+W_(W+1)",
  "W_(W+1)+W_(W+1)+W_(W+1)+W_W",
  "W_(W+1)+W_(W+1)+W_(W+1)+W_w",
  "W_(W+1)+W_(W+1)+W_(W+1)+W_2",
  "W_(W+1)+W_(W+1)+W_(W+1)+W",
  "W_(W+1)+W_(W+1)+W_(W+1)+w",
  "W_(W+1)+W_(W+1)+W_(W+1)+1",
  "W_(W+1)+W_(W+1)+W_W+W_W",
  "W_(W+1)+W_(W+1)+W_W+W_w",
  "W_(W+1)+W_(W+1)+W_W+W_2",
  "W_(W+1)+W_(W+1)+W_W+W",
  "W_(W+1)+W_(W+1)+W_W+w",
  "W_(W+1)+W_(W+1)+W_W+1",
  "W_(W+1)+W_(W+1)+W_w+W_w",
  "W_(W+1)+W_(W+1)+W_w+W_2",
  "W_(W+1)+W_(W+1)+W_w+W",
  "W_(W+1)+W_(W+1)+W_w+w",
  "W_(W+1)+W_(W+1)+W_w+1",
  "W_(W+1)+W_(W+1)+W_2+W_2",
  "W_(W+1)+W_(W+1)+W_2+W",
  "W_(W+1)+W_(W+1)+W_2+w",
  "W_(W+1)+W_(W+1)+W_2+1",
  "W_(W+1)+W_(W+1)+W+W",
  "W_(W+1)+W_(W+1)+W+w",
  "W_(W+1)+W_(W+1)+W+1",
  "W_(W+1)+W_(W+1)+w+w",
  "W_(W+1)+W_(W+1)+w+1",
  "W_(W+1)+W_(W+1)+1+1",
  "W_(W+1)+W_W+W_W+W_W",
  "W_(W+1)+W_W+W_W+W_w",
  "W_(W+1)+W_W+W_W+W_2",
  "W_(W+1)+W_W+W_W+W",
  "W_(W+1)+W_W+W_W+w",
  "W_(W+1)+W_W+W_W+1",
  "W_(W+1)+W_W+W_w+W_w",
  "W_(W+1)+W_W+W_w+W_2",
  "W_(W+1)+W_W+W_w+W",
  "W_(W+1)+W_W+W_w+w",
  "W_(W+1)+W_W+W_w+1",
  "W_(W+1)+W_W+W_2+W_2",
  "W_(W+1)+W_W+W_2+W",
  "W_(W+1)+W_W+W_2+w",
  "W_(W+1)+W_W+W_2+1",
  "W_(W+1)+W_W+W+W",
  "W_(W+1)+W_W+W+w",
  "W_(W+1)+W_W+W+1",
  "W_(W+1)+W_W+w+w",
  "W_(W+1)+W_W+w+1",
  "W_(W+1)+W_W+1+1",
  "W_(W+1)+W_w+W_w+W_w",
  "W_(W+1)+W_w+W_w+W_2",
  "W_(W+1)+W_w+W_w+W",
  "W_(W+1)+W_w+W_w+w",
  "W_(W+1)+W_w+W_w+1",
  "W_(W+1)+W_w+W_2+W_2",
  "W_(W+1)+W_w+W_2+W",
  "W_(W+1)+W_w+W_2+w",
  "W_(W+1)+W_w+W_2+1",
  "W_(W+1)+W_w+W+W",
  "W_(W+1)+W_w+W+w",
  "W_(W+1)+W_w+W+1",
  "W_(W+1)+W_w+w+w",
  "W_(W+1)+W_w+w+1",
  "W_(W+1)+W_w+1+1",
  "W_(W+1)+W_2+W_2+W_2",
  "W_(W+1)+W_2+W_2+W",
  "W_(W+1)+W_2+W_2+w",
  "W_(W+1)+W_2+W_2+1",
  "W_(W+1)+W_2+W+W",
  "W_(W+1)+W_2+W+w",
  "W_(W+1)+W_2+W+1",
  "W_(W+1)+W_2+w+w",
  "W_(W+1)+W_2+w+1",
  "W_(W+1)+W_2+1+1",
  "W_(W+1)+W+W+W",
  "W_(W+1)+W+W+w",
  "W_(W+1)+W+W+1",
  "W_(W+1)+W+w+w",
  "W_(W+1)+W+w+1",
  "W_(W+1)+W+1+1",
  "W_(W+1)+w+w+w",
  "W_(W+1)+w+w+1",
  "W_(W+1)+w+1+1",
  "W_(W+1)+1+1+1",
  "W_(W+1)*w",
  "W_(W+1)*W_w"]

#guard famRWp1.length = 122
#guard famCounts famRWp1 = (501, 21, 704, 50, (0, 203))

/-- Sums of up to three terms after `Ω_{Ω_{Ω+1}}` from `1, ω, Ω, Ω_2, Ω_ω, Ω_Ω, Ω_{Ω+1}, Ω_{Ω_{Ω+1}}` (Fix M; `TrioFixNonLastOther` breaks 153), and products. -/
def famRWW1 : List String := [
  "W_W_(W+1)",
  "W_W_(W+1)+W_W_(W+1)",
  "W_W_(W+1)+W_(W+1)",
  "W_W_(W+1)+W_W",
  "W_W_(W+1)+W_w",
  "W_W_(W+1)+W_2",
  "W_W_(W+1)+W",
  "W_W_(W+1)+w",
  "W_W_(W+1)+1",
  "W_W_(W+1)+W_W_(W+1)+W_W_(W+1)",
  "W_W_(W+1)+W_W_(W+1)+W_(W+1)",
  "W_W_(W+1)+W_W_(W+1)+W_W",
  "W_W_(W+1)+W_W_(W+1)+W_w",
  "W_W_(W+1)+W_W_(W+1)+W_2",
  "W_W_(W+1)+W_W_(W+1)+W",
  "W_W_(W+1)+W_W_(W+1)+w",
  "W_W_(W+1)+W_W_(W+1)+1",
  "W_W_(W+1)+W_(W+1)+W_(W+1)",
  "W_W_(W+1)+W_(W+1)+W_W",
  "W_W_(W+1)+W_(W+1)+W_w",
  "W_W_(W+1)+W_(W+1)+W_2",
  "W_W_(W+1)+W_(W+1)+W",
  "W_W_(W+1)+W_(W+1)+w",
  "W_W_(W+1)+W_(W+1)+1",
  "W_W_(W+1)+W_W+W_W",
  "W_W_(W+1)+W_W+W_w",
  "W_W_(W+1)+W_W+W_2",
  "W_W_(W+1)+W_W+W",
  "W_W_(W+1)+W_W+w",
  "W_W_(W+1)+W_W+1",
  "W_W_(W+1)+W_w+W_w",
  "W_W_(W+1)+W_w+W_2",
  "W_W_(W+1)+W_w+W",
  "W_W_(W+1)+W_w+w",
  "W_W_(W+1)+W_w+1",
  "W_W_(W+1)+W_2+W_2",
  "W_W_(W+1)+W_2+W",
  "W_W_(W+1)+W_2+w",
  "W_W_(W+1)+W_2+1",
  "W_W_(W+1)+W+W",
  "W_W_(W+1)+W+w",
  "W_W_(W+1)+W+1",
  "W_W_(W+1)+w+w",
  "W_W_(W+1)+w+1",
  "W_W_(W+1)+1+1",
  "W_W_(W+1)+W_W_(W+1)+W_W_(W+1)+W_W_(W+1)",
  "W_W_(W+1)+W_W_(W+1)+W_W_(W+1)+W_(W+1)",
  "W_W_(W+1)+W_W_(W+1)+W_W_(W+1)+W_W",
  "W_W_(W+1)+W_W_(W+1)+W_W_(W+1)+W_w",
  "W_W_(W+1)+W_W_(W+1)+W_W_(W+1)+W_2",
  "W_W_(W+1)+W_W_(W+1)+W_W_(W+1)+W",
  "W_W_(W+1)+W_W_(W+1)+W_W_(W+1)+w",
  "W_W_(W+1)+W_W_(W+1)+W_W_(W+1)+1",
  "W_W_(W+1)+W_W_(W+1)+W_(W+1)+W_(W+1)",
  "W_W_(W+1)+W_W_(W+1)+W_(W+1)+W_W",
  "W_W_(W+1)+W_W_(W+1)+W_(W+1)+W_w",
  "W_W_(W+1)+W_W_(W+1)+W_(W+1)+W_2",
  "W_W_(W+1)+W_W_(W+1)+W_(W+1)+W",
  "W_W_(W+1)+W_W_(W+1)+W_(W+1)+w",
  "W_W_(W+1)+W_W_(W+1)+W_(W+1)+1",
  "W_W_(W+1)+W_W_(W+1)+W_W+W_W",
  "W_W_(W+1)+W_W_(W+1)+W_W+W_w",
  "W_W_(W+1)+W_W_(W+1)+W_W+W_2",
  "W_W_(W+1)+W_W_(W+1)+W_W+W",
  "W_W_(W+1)+W_W_(W+1)+W_W+w",
  "W_W_(W+1)+W_W_(W+1)+W_W+1",
  "W_W_(W+1)+W_W_(W+1)+W_w+W_w",
  "W_W_(W+1)+W_W_(W+1)+W_w+W_2",
  "W_W_(W+1)+W_W_(W+1)+W_w+W",
  "W_W_(W+1)+W_W_(W+1)+W_w+w",
  "W_W_(W+1)+W_W_(W+1)+W_w+1",
  "W_W_(W+1)+W_W_(W+1)+W_2+W_2",
  "W_W_(W+1)+W_W_(W+1)+W_2+W",
  "W_W_(W+1)+W_W_(W+1)+W_2+w",
  "W_W_(W+1)+W_W_(W+1)+W_2+1",
  "W_W_(W+1)+W_W_(W+1)+W+W",
  "W_W_(W+1)+W_W_(W+1)+W+w",
  "W_W_(W+1)+W_W_(W+1)+W+1",
  "W_W_(W+1)+W_W_(W+1)+w+w",
  "W_W_(W+1)+W_W_(W+1)+w+1",
  "W_W_(W+1)+W_W_(W+1)+1+1",
  "W_W_(W+1)+W_(W+1)+W_(W+1)+W_(W+1)",
  "W_W_(W+1)+W_(W+1)+W_(W+1)+W_W",
  "W_W_(W+1)+W_(W+1)+W_(W+1)+W_w",
  "W_W_(W+1)+W_(W+1)+W_(W+1)+W_2",
  "W_W_(W+1)+W_(W+1)+W_(W+1)+W",
  "W_W_(W+1)+W_(W+1)+W_(W+1)+w",
  "W_W_(W+1)+W_(W+1)+W_(W+1)+1",
  "W_W_(W+1)+W_(W+1)+W_W+W_W",
  "W_W_(W+1)+W_(W+1)+W_W+W_w",
  "W_W_(W+1)+W_(W+1)+W_W+W_2",
  "W_W_(W+1)+W_(W+1)+W_W+W",
  "W_W_(W+1)+W_(W+1)+W_W+w",
  "W_W_(W+1)+W_(W+1)+W_W+1",
  "W_W_(W+1)+W_(W+1)+W_w+W_w",
  "W_W_(W+1)+W_(W+1)+W_w+W_2",
  "W_W_(W+1)+W_(W+1)+W_w+W",
  "W_W_(W+1)+W_(W+1)+W_w+w",
  "W_W_(W+1)+W_(W+1)+W_w+1",
  "W_W_(W+1)+W_(W+1)+W_2+W_2",
  "W_W_(W+1)+W_(W+1)+W_2+W",
  "W_W_(W+1)+W_(W+1)+W_2+w",
  "W_W_(W+1)+W_(W+1)+W_2+1",
  "W_W_(W+1)+W_(W+1)+W+W",
  "W_W_(W+1)+W_(W+1)+W+w",
  "W_W_(W+1)+W_(W+1)+W+1",
  "W_W_(W+1)+W_(W+1)+w+w",
  "W_W_(W+1)+W_(W+1)+w+1",
  "W_W_(W+1)+W_(W+1)+1+1",
  "W_W_(W+1)+W_W+W_W+W_W",
  "W_W_(W+1)+W_W+W_W+W_w",
  "W_W_(W+1)+W_W+W_W+W_2",
  "W_W_(W+1)+W_W+W_W+W",
  "W_W_(W+1)+W_W+W_W+w",
  "W_W_(W+1)+W_W+W_W+1",
  "W_W_(W+1)+W_W+W_w+W_w",
  "W_W_(W+1)+W_W+W_w+W_2",
  "W_W_(W+1)+W_W+W_w+W",
  "W_W_(W+1)+W_W+W_w+w",
  "W_W_(W+1)+W_W+W_w+1",
  "W_W_(W+1)+W_W+W_2+W_2",
  "W_W_(W+1)+W_W+W_2+W",
  "W_W_(W+1)+W_W+W_2+w",
  "W_W_(W+1)+W_W+W_2+1",
  "W_W_(W+1)+W_W+W+W",
  "W_W_(W+1)+W_W+W+w",
  "W_W_(W+1)+W_W+W+1",
  "W_W_(W+1)+W_W+w+w",
  "W_W_(W+1)+W_W+w+1",
  "W_W_(W+1)+W_W+1+1",
  "W_W_(W+1)+W_w+W_w+W_w",
  "W_W_(W+1)+W_w+W_w+W_2",
  "W_W_(W+1)+W_w+W_w+W",
  "W_W_(W+1)+W_w+W_w+w",
  "W_W_(W+1)+W_w+W_w+1",
  "W_W_(W+1)+W_w+W_2+W_2",
  "W_W_(W+1)+W_w+W_2+W",
  "W_W_(W+1)+W_w+W_2+w",
  "W_W_(W+1)+W_w+W_2+1",
  "W_W_(W+1)+W_w+W+W",
  "W_W_(W+1)+W_w+W+w",
  "W_W_(W+1)+W_w+W+1",
  "W_W_(W+1)+W_w+w+w",
  "W_W_(W+1)+W_w+w+1",
  "W_W_(W+1)+W_w+1+1",
  "W_W_(W+1)+W_2+W_2+W_2",
  "W_W_(W+1)+W_2+W_2+W",
  "W_W_(W+1)+W_2+W_2+w",
  "W_W_(W+1)+W_2+W_2+1",
  "W_W_(W+1)+W_2+W+W",
  "W_W_(W+1)+W_2+W+w",
  "W_W_(W+1)+W_2+W+1",
  "W_W_(W+1)+W_2+w+w",
  "W_W_(W+1)+W_2+w+1",
  "W_W_(W+1)+W_2+1+1",
  "W_W_(W+1)+W+W+W",
  "W_W_(W+1)+W+W+w",
  "W_W_(W+1)+W+W+1",
  "W_W_(W+1)+W+w+w",
  "W_W_(W+1)+W+w+1",
  "W_W_(W+1)+W+1+1",
  "W_W_(W+1)+w+w+w",
  "W_W_(W+1)+w+w+1",
  "W_W_(W+1)+w+1+1",
  "W_W_(W+1)+1+1+1",
  "W_W_(W+1)*w"]

#guard famRWW1.length = 166
#guard famCounts famRWW1 = (544, 24, 762, 57, (0, 218))

/-- Sums of up to three terms after `Ω_{Ω_{ω·2}}` from `1, ω, Ω, Ω_ω, Ω_{ω+1}, Ω_{ω·2}, Ω_Ω, Ω_{Ω_{ω·2}}` (Fix G, change 1; `TrioFixNonLastOther` breaks 1,052). -/
def famRw2 : List String := [
  "W_W_(w2)",
  "W_W_(w2)+W_W_(w2)",
  "W_W_(w2)+W_W",
  "W_W_(w2)+W_(w2)",
  "W_W_(w2)+W_(w+1)",
  "W_W_(w2)+W_w",
  "W_W_(w2)+W",
  "W_W_(w2)+w",
  "W_W_(w2)+1",
  "W_W_(w2)+W_W_(w2)+W_W_(w2)",
  "W_W_(w2)+W_W_(w2)+W_W",
  "W_W_(w2)+W_W_(w2)+W_(w2)",
  "W_W_(w2)+W_W_(w2)+W_(w+1)",
  "W_W_(w2)+W_W_(w2)+W_w",
  "W_W_(w2)+W_W_(w2)+W",
  "W_W_(w2)+W_W_(w2)+w",
  "W_W_(w2)+W_W_(w2)+1",
  "W_W_(w2)+W_W+W_W",
  "W_W_(w2)+W_W+W_(w2)",
  "W_W_(w2)+W_W+W_(w+1)",
  "W_W_(w2)+W_W+W_w",
  "W_W_(w2)+W_W+W",
  "W_W_(w2)+W_W+w",
  "W_W_(w2)+W_W+1",
  "W_W_(w2)+W_(w2)+W_(w2)",
  "W_W_(w2)+W_(w2)+W_(w+1)",
  "W_W_(w2)+W_(w2)+W_w",
  "W_W_(w2)+W_(w2)+W",
  "W_W_(w2)+W_(w2)+w",
  "W_W_(w2)+W_(w2)+1",
  "W_W_(w2)+W_(w+1)+W_(w+1)",
  "W_W_(w2)+W_(w+1)+W_w",
  "W_W_(w2)+W_(w+1)+W",
  "W_W_(w2)+W_(w+1)+w",
  "W_W_(w2)+W_(w+1)+1",
  "W_W_(w2)+W_w+W_w",
  "W_W_(w2)+W_w+W",
  "W_W_(w2)+W_w+w",
  "W_W_(w2)+W_w+1",
  "W_W_(w2)+W+W",
  "W_W_(w2)+W+w",
  "W_W_(w2)+W+1",
  "W_W_(w2)+w+w",
  "W_W_(w2)+w+1",
  "W_W_(w2)+1+1",
  "W_W_(w2)+W_W_(w2)+W_W_(w2)+W_W_(w2)",
  "W_W_(w2)+W_W_(w2)+W_W_(w2)+W_W",
  "W_W_(w2)+W_W_(w2)+W_W_(w2)+W_(w2)",
  "W_W_(w2)+W_W_(w2)+W_W_(w2)+W_(w+1)",
  "W_W_(w2)+W_W_(w2)+W_W_(w2)+W_w",
  "W_W_(w2)+W_W_(w2)+W_W_(w2)+W",
  "W_W_(w2)+W_W_(w2)+W_W_(w2)+w",
  "W_W_(w2)+W_W_(w2)+W_W_(w2)+1",
  "W_W_(w2)+W_W_(w2)+W_W+W_W",
  "W_W_(w2)+W_W_(w2)+W_W+W_(w2)",
  "W_W_(w2)+W_W_(w2)+W_W+W_(w+1)",
  "W_W_(w2)+W_W_(w2)+W_W+W_w",
  "W_W_(w2)+W_W_(w2)+W_W+W",
  "W_W_(w2)+W_W_(w2)+W_W+w",
  "W_W_(w2)+W_W_(w2)+W_W+1",
  "W_W_(w2)+W_W_(w2)+W_(w2)+W_(w2)",
  "W_W_(w2)+W_W_(w2)+W_(w2)+W_(w+1)",
  "W_W_(w2)+W_W_(w2)+W_(w2)+W_w",
  "W_W_(w2)+W_W_(w2)+W_(w2)+W",
  "W_W_(w2)+W_W_(w2)+W_(w2)+w",
  "W_W_(w2)+W_W_(w2)+W_(w2)+1",
  "W_W_(w2)+W_W_(w2)+W_(w+1)+W_(w+1)",
  "W_W_(w2)+W_W_(w2)+W_(w+1)+W_w",
  "W_W_(w2)+W_W_(w2)+W_(w+1)+W",
  "W_W_(w2)+W_W_(w2)+W_(w+1)+w",
  "W_W_(w2)+W_W_(w2)+W_(w+1)+1",
  "W_W_(w2)+W_W_(w2)+W_w+W_w",
  "W_W_(w2)+W_W_(w2)+W_w+W",
  "W_W_(w2)+W_W_(w2)+W_w+w",
  "W_W_(w2)+W_W_(w2)+W_w+1",
  "W_W_(w2)+W_W_(w2)+W+W",
  "W_W_(w2)+W_W_(w2)+W+w",
  "W_W_(w2)+W_W_(w2)+W+1",
  "W_W_(w2)+W_W_(w2)+w+w",
  "W_W_(w2)+W_W_(w2)+w+1",
  "W_W_(w2)+W_W_(w2)+1+1",
  "W_W_(w2)+W_W+W_W+W_W",
  "W_W_(w2)+W_W+W_W+W_(w2)",
  "W_W_(w2)+W_W+W_W+W_(w+1)",
  "W_W_(w2)+W_W+W_W+W_w",
  "W_W_(w2)+W_W+W_W+W",
  "W_W_(w2)+W_W+W_W+w",
  "W_W_(w2)+W_W+W_W+1",
  "W_W_(w2)+W_W+W_(w2)+W_(w2)",
  "W_W_(w2)+W_W+W_(w2)+W_(w+1)",
  "W_W_(w2)+W_W+W_(w2)+W_w",
  "W_W_(w2)+W_W+W_(w2)+W",
  "W_W_(w2)+W_W+W_(w2)+w",
  "W_W_(w2)+W_W+W_(w2)+1",
  "W_W_(w2)+W_W+W_(w+1)+W_(w+1)",
  "W_W_(w2)+W_W+W_(w+1)+W_w",
  "W_W_(w2)+W_W+W_(w+1)+W",
  "W_W_(w2)+W_W+W_(w+1)+w",
  "W_W_(w2)+W_W+W_(w+1)+1",
  "W_W_(w2)+W_W+W_w+W_w",
  "W_W_(w2)+W_W+W_w+W",
  "W_W_(w2)+W_W+W_w+w",
  "W_W_(w2)+W_W+W_w+1",
  "W_W_(w2)+W_W+W+W",
  "W_W_(w2)+W_W+W+w",
  "W_W_(w2)+W_W+W+1",
  "W_W_(w2)+W_W+w+w",
  "W_W_(w2)+W_W+w+1",
  "W_W_(w2)+W_W+1+1",
  "W_W_(w2)+W_(w2)+W_(w2)+W_(w2)",
  "W_W_(w2)+W_(w2)+W_(w2)+W_(w+1)",
  "W_W_(w2)+W_(w2)+W_(w2)+W_w",
  "W_W_(w2)+W_(w2)+W_(w2)+W",
  "W_W_(w2)+W_(w2)+W_(w2)+w",
  "W_W_(w2)+W_(w2)+W_(w2)+1",
  "W_W_(w2)+W_(w2)+W_(w+1)+W_(w+1)",
  "W_W_(w2)+W_(w2)+W_(w+1)+W_w",
  "W_W_(w2)+W_(w2)+W_(w+1)+W",
  "W_W_(w2)+W_(w2)+W_(w+1)+w",
  "W_W_(w2)+W_(w2)+W_(w+1)+1",
  "W_W_(w2)+W_(w2)+W_w+W_w",
  "W_W_(w2)+W_(w2)+W_w+W",
  "W_W_(w2)+W_(w2)+W_w+w",
  "W_W_(w2)+W_(w2)+W_w+1",
  "W_W_(w2)+W_(w2)+W+W",
  "W_W_(w2)+W_(w2)+W+w",
  "W_W_(w2)+W_(w2)+W+1",
  "W_W_(w2)+W_(w2)+w+w",
  "W_W_(w2)+W_(w2)+w+1",
  "W_W_(w2)+W_(w2)+1+1",
  "W_W_(w2)+W_(w+1)+W_(w+1)+W_(w+1)",
  "W_W_(w2)+W_(w+1)+W_(w+1)+W_w",
  "W_W_(w2)+W_(w+1)+W_(w+1)+W",
  "W_W_(w2)+W_(w+1)+W_(w+1)+w",
  "W_W_(w2)+W_(w+1)+W_(w+1)+1",
  "W_W_(w2)+W_(w+1)+W_w+W_w",
  "W_W_(w2)+W_(w+1)+W_w+W",
  "W_W_(w2)+W_(w+1)+W_w+w",
  "W_W_(w2)+W_(w+1)+W_w+1",
  "W_W_(w2)+W_(w+1)+W+W",
  "W_W_(w2)+W_(w+1)+W+w",
  "W_W_(w2)+W_(w+1)+W+1",
  "W_W_(w2)+W_(w+1)+w+w",
  "W_W_(w2)+W_(w+1)+w+1",
  "W_W_(w2)+W_(w+1)+1+1",
  "W_W_(w2)+W_w+W_w+W_w",
  "W_W_(w2)+W_w+W_w+W",
  "W_W_(w2)+W_w+W_w+w",
  "W_W_(w2)+W_w+W_w+1",
  "W_W_(w2)+W_w+W+W",
  "W_W_(w2)+W_w+W+w",
  "W_W_(w2)+W_w+W+1",
  "W_W_(w2)+W_w+w+w",
  "W_W_(w2)+W_w+w+1",
  "W_W_(w2)+W_w+1+1",
  "W_W_(w2)+W+W+W",
  "W_W_(w2)+W+W+w",
  "W_W_(w2)+W+W+1",
  "W_W_(w2)+W+w+w",
  "W_W_(w2)+W+w+1",
  "W_W_(w2)+W+1+1",
  "W_W_(w2)+w+w+w",
  "W_W_(w2)+w+w+1",
  "W_W_(w2)+w+1+1",
  "W_W_(w2)+1+1+1"]

#guard famRw2.length = 165
#guard famCounts famRw2 = (1620, 0, 1728, 27, (0, 108))

/-- Sums of up to three terms after `Ω_{Ω_{ω^2}}` from `1, ω, Ω, Ω_ω, Ω_{ω·2}, Ω_{ω^2}, Ω_Ω, Ω_{Ω_{ω^2}}` (change 1; `TrioFixNonLastOther` breaks 182; 8 still broken), and products. -/
def famRww : List String := [
  "W_W_(w^2)",
  "W_W_(w^2)+W_W_(w^2)",
  "W_W_(w^2)+W_W",
  "W_W_(w^2)+W_(w^2)",
  "W_W_(w^2)+W_(w2)",
  "W_W_(w^2)+W_w",
  "W_W_(w^2)+W",
  "W_W_(w^2)+w",
  "W_W_(w^2)+1",
  "W_W_(w^2)+W_W_(w^2)+W_W_(w^2)",
  "W_W_(w^2)+W_W_(w^2)+W_W",
  "W_W_(w^2)+W_W_(w^2)+W_(w^2)",
  "W_W_(w^2)+W_W_(w^2)+W_(w2)",
  "W_W_(w^2)+W_W_(w^2)+W_w",
  "W_W_(w^2)+W_W_(w^2)+W",
  "W_W_(w^2)+W_W_(w^2)+w",
  "W_W_(w^2)+W_W_(w^2)+1",
  "W_W_(w^2)+W_W+W_W",
  "W_W_(w^2)+W_W+W_(w^2)",
  "W_W_(w^2)+W_W+W_(w2)",
  "W_W_(w^2)+W_W+W_w",
  "W_W_(w^2)+W_W+W",
  "W_W_(w^2)+W_W+w",
  "W_W_(w^2)+W_W+1",
  "W_W_(w^2)+W_(w^2)+W_(w^2)",
  "W_W_(w^2)+W_(w^2)+W_(w2)",
  "W_W_(w^2)+W_(w^2)+W_w",
  "W_W_(w^2)+W_(w^2)+W",
  "W_W_(w^2)+W_(w^2)+w",
  "W_W_(w^2)+W_(w^2)+1",
  "W_W_(w^2)+W_(w2)+W_(w2)",
  "W_W_(w^2)+W_(w2)+W_w",
  "W_W_(w^2)+W_(w2)+W",
  "W_W_(w^2)+W_(w2)+w",
  "W_W_(w^2)+W_(w2)+1",
  "W_W_(w^2)+W_w+W_w",
  "W_W_(w^2)+W_w+W",
  "W_W_(w^2)+W_w+w",
  "W_W_(w^2)+W_w+1",
  "W_W_(w^2)+W+W",
  "W_W_(w^2)+W+w",
  "W_W_(w^2)+W+1",
  "W_W_(w^2)+w+w",
  "W_W_(w^2)+w+1",
  "W_W_(w^2)+1+1",
  "W_W_(w^2)+W_W_(w^2)+W_W_(w^2)+W_W_(w^2)",
  "W_W_(w^2)+W_W_(w^2)+W_W_(w^2)+W_W",
  "W_W_(w^2)+W_W_(w^2)+W_W_(w^2)+W_(w^2)",
  "W_W_(w^2)+W_W_(w^2)+W_W_(w^2)+W_(w2)",
  "W_W_(w^2)+W_W_(w^2)+W_W_(w^2)+W_w",
  "W_W_(w^2)+W_W_(w^2)+W_W_(w^2)+W",
  "W_W_(w^2)+W_W_(w^2)+W_W_(w^2)+w",
  "W_W_(w^2)+W_W_(w^2)+W_W_(w^2)+1",
  "W_W_(w^2)+W_W_(w^2)+W_W+W_W",
  "W_W_(w^2)+W_W_(w^2)+W_W+W_(w^2)",
  "W_W_(w^2)+W_W_(w^2)+W_W+W_(w2)",
  "W_W_(w^2)+W_W_(w^2)+W_W+W_w",
  "W_W_(w^2)+W_W_(w^2)+W_W+W",
  "W_W_(w^2)+W_W_(w^2)+W_W+w",
  "W_W_(w^2)+W_W_(w^2)+W_W+1",
  "W_W_(w^2)+W_W_(w^2)+W_(w^2)+W_(w^2)",
  "W_W_(w^2)+W_W_(w^2)+W_(w^2)+W_(w2)",
  "W_W_(w^2)+W_W_(w^2)+W_(w^2)+W_w",
  "W_W_(w^2)+W_W_(w^2)+W_(w^2)+W",
  "W_W_(w^2)+W_W_(w^2)+W_(w^2)+w",
  "W_W_(w^2)+W_W_(w^2)+W_(w^2)+1",
  "W_W_(w^2)+W_W_(w^2)+W_(w2)+W_(w2)",
  "W_W_(w^2)+W_W_(w^2)+W_(w2)+W_w",
  "W_W_(w^2)+W_W_(w^2)+W_(w2)+W",
  "W_W_(w^2)+W_W_(w^2)+W_(w2)+w",
  "W_W_(w^2)+W_W_(w^2)+W_(w2)+1",
  "W_W_(w^2)+W_W_(w^2)+W_w+W_w",
  "W_W_(w^2)+W_W_(w^2)+W_w+W",
  "W_W_(w^2)+W_W_(w^2)+W_w+w",
  "W_W_(w^2)+W_W_(w^2)+W_w+1",
  "W_W_(w^2)+W_W_(w^2)+W+W",
  "W_W_(w^2)+W_W_(w^2)+W+w",
  "W_W_(w^2)+W_W_(w^2)+W+1",
  "W_W_(w^2)+W_W_(w^2)+w+w",
  "W_W_(w^2)+W_W_(w^2)+w+1",
  "W_W_(w^2)+W_W_(w^2)+1+1",
  "W_W_(w^2)+W_W+W_W+W_W",
  "W_W_(w^2)+W_W+W_W+W_(w^2)",
  "W_W_(w^2)+W_W+W_W+W_(w2)",
  "W_W_(w^2)+W_W+W_W+W_w",
  "W_W_(w^2)+W_W+W_W+W",
  "W_W_(w^2)+W_W+W_W+w",
  "W_W_(w^2)+W_W+W_W+1",
  "W_W_(w^2)+W_W+W_(w^2)+W_(w^2)",
  "W_W_(w^2)+W_W+W_(w^2)+W_(w2)",
  "W_W_(w^2)+W_W+W_(w^2)+W_w",
  "W_W_(w^2)+W_W+W_(w^2)+W",
  "W_W_(w^2)+W_W+W_(w^2)+w",
  "W_W_(w^2)+W_W+W_(w^2)+1",
  "W_W_(w^2)+W_W+W_(w2)+W_(w2)",
  "W_W_(w^2)+W_W+W_(w2)+W_w",
  "W_W_(w^2)+W_W+W_(w2)+W",
  "W_W_(w^2)+W_W+W_(w2)+w",
  "W_W_(w^2)+W_W+W_(w2)+1",
  "W_W_(w^2)+W_W+W_w+W_w",
  "W_W_(w^2)+W_W+W_w+W",
  "W_W_(w^2)+W_W+W_w+w",
  "W_W_(w^2)+W_W+W_w+1",
  "W_W_(w^2)+W_W+W+W",
  "W_W_(w^2)+W_W+W+w",
  "W_W_(w^2)+W_W+W+1",
  "W_W_(w^2)+W_W+w+w",
  "W_W_(w^2)+W_W+w+1",
  "W_W_(w^2)+W_W+1+1",
  "W_W_(w^2)+W_(w^2)+W_(w^2)+W_(w^2)",
  "W_W_(w^2)+W_(w^2)+W_(w^2)+W_(w2)",
  "W_W_(w^2)+W_(w^2)+W_(w^2)+W_w",
  "W_W_(w^2)+W_(w^2)+W_(w^2)+W",
  "W_W_(w^2)+W_(w^2)+W_(w^2)+w",
  "W_W_(w^2)+W_(w^2)+W_(w^2)+1",
  "W_W_(w^2)+W_(w^2)+W_(w2)+W_(w2)",
  "W_W_(w^2)+W_(w^2)+W_(w2)+W_w",
  "W_W_(w^2)+W_(w^2)+W_(w2)+W",
  "W_W_(w^2)+W_(w^2)+W_(w2)+w",
  "W_W_(w^2)+W_(w^2)+W_(w2)+1",
  "W_W_(w^2)+W_(w^2)+W_w+W_w",
  "W_W_(w^2)+W_(w^2)+W_w+W",
  "W_W_(w^2)+W_(w^2)+W_w+w",
  "W_W_(w^2)+W_(w^2)+W_w+1",
  "W_W_(w^2)+W_(w^2)+W+W",
  "W_W_(w^2)+W_(w^2)+W+w",
  "W_W_(w^2)+W_(w^2)+W+1",
  "W_W_(w^2)+W_(w^2)+w+w",
  "W_W_(w^2)+W_(w^2)+w+1",
  "W_W_(w^2)+W_(w^2)+1+1",
  "W_W_(w^2)+W_(w2)+W_(w2)+W_(w2)",
  "W_W_(w^2)+W_(w2)+W_(w2)+W_w",
  "W_W_(w^2)+W_(w2)+W_(w2)+W",
  "W_W_(w^2)+W_(w2)+W_(w2)+w",
  "W_W_(w^2)+W_(w2)+W_(w2)+1",
  "W_W_(w^2)+W_(w2)+W_w+W_w",
  "W_W_(w^2)+W_(w2)+W_w+W",
  "W_W_(w^2)+W_(w2)+W_w+w",
  "W_W_(w^2)+W_(w2)+W_w+1",
  "W_W_(w^2)+W_(w2)+W+W",
  "W_W_(w^2)+W_(w2)+W+w",
  "W_W_(w^2)+W_(w2)+W+1",
  "W_W_(w^2)+W_(w2)+w+w",
  "W_W_(w^2)+W_(w2)+w+1",
  "W_W_(w^2)+W_(w2)+1+1",
  "W_W_(w^2)+W_w+W_w+W_w",
  "W_W_(w^2)+W_w+W_w+W",
  "W_W_(w^2)+W_w+W_w+w",
  "W_W_(w^2)+W_w+W_w+1",
  "W_W_(w^2)+W_w+W+W",
  "W_W_(w^2)+W_w+W+w",
  "W_W_(w^2)+W_w+W+1",
  "W_W_(w^2)+W_w+w+w",
  "W_W_(w^2)+W_w+w+1",
  "W_W_(w^2)+W_w+1+1",
  "W_W_(w^2)+W+W+W",
  "W_W_(w^2)+W+W+w",
  "W_W_(w^2)+W+W+1",
  "W_W_(w^2)+W+w+w",
  "W_W_(w^2)+W+w+1",
  "W_W_(w^2)+W+1+1",
  "W_W_(w^2)+w+w+w",
  "W_W_(w^2)+w+w+1",
  "W_W_(w^2)+w+1+1",
  "W_W_(w^2)+1+1+1",
  "W_W_(w^2)*w"]

#guard famRww.length = 166
#guard famCounts famRww = (1296, 15, 2940, 115, (8, 1652))

/-- Sums of up to three terms after `Ω_{Ω_{ω+1}}` from `1, ω, Ω, Ω_ω, Ω_{ω+1}, Ω_Ω, Ω_{Ω_{ω+1}}` (Fix G; `TrioFixNonLastOther` breaks 319; 6 still broken). -/
def famRwp1 : List String := [
  "W_W_(w+1)",
  "W_W_(w+1)+W_W_(w+1)",
  "W_W_(w+1)+W_W",
  "W_W_(w+1)+W_(w+1)",
  "W_W_(w+1)+W_w",
  "W_W_(w+1)+W",
  "W_W_(w+1)+w",
  "W_W_(w+1)+1",
  "W_W_(w+1)+W_W_(w+1)+W_W_(w+1)",
  "W_W_(w+1)+W_W_(w+1)+W_W",
  "W_W_(w+1)+W_W_(w+1)+W_(w+1)",
  "W_W_(w+1)+W_W_(w+1)+W_w",
  "W_W_(w+1)+W_W_(w+1)+W",
  "W_W_(w+1)+W_W_(w+1)+w",
  "W_W_(w+1)+W_W_(w+1)+1",
  "W_W_(w+1)+W_W+W_W",
  "W_W_(w+1)+W_W+W_(w+1)",
  "W_W_(w+1)+W_W+W_w",
  "W_W_(w+1)+W_W+W",
  "W_W_(w+1)+W_W+w",
  "W_W_(w+1)+W_W+1",
  "W_W_(w+1)+W_(w+1)+W_(w+1)",
  "W_W_(w+1)+W_(w+1)+W_w",
  "W_W_(w+1)+W_(w+1)+W",
  "W_W_(w+1)+W_(w+1)+w",
  "W_W_(w+1)+W_(w+1)+1",
  "W_W_(w+1)+W_w+W_w",
  "W_W_(w+1)+W_w+W",
  "W_W_(w+1)+W_w+w",
  "W_W_(w+1)+W_w+1",
  "W_W_(w+1)+W+W",
  "W_W_(w+1)+W+w",
  "W_W_(w+1)+W+1",
  "W_W_(w+1)+w+w",
  "W_W_(w+1)+w+1",
  "W_W_(w+1)+1+1",
  "W_W_(w+1)+W_W_(w+1)+W_W_(w+1)+W_W_(w+1)",
  "W_W_(w+1)+W_W_(w+1)+W_W_(w+1)+W_W",
  "W_W_(w+1)+W_W_(w+1)+W_W_(w+1)+W_(w+1)",
  "W_W_(w+1)+W_W_(w+1)+W_W_(w+1)+W_w",
  "W_W_(w+1)+W_W_(w+1)+W_W_(w+1)+W",
  "W_W_(w+1)+W_W_(w+1)+W_W_(w+1)+w",
  "W_W_(w+1)+W_W_(w+1)+W_W_(w+1)+1",
  "W_W_(w+1)+W_W_(w+1)+W_W+W_W",
  "W_W_(w+1)+W_W_(w+1)+W_W+W_(w+1)",
  "W_W_(w+1)+W_W_(w+1)+W_W+W_w",
  "W_W_(w+1)+W_W_(w+1)+W_W+W",
  "W_W_(w+1)+W_W_(w+1)+W_W+w",
  "W_W_(w+1)+W_W_(w+1)+W_W+1",
  "W_W_(w+1)+W_W_(w+1)+W_(w+1)+W_(w+1)",
  "W_W_(w+1)+W_W_(w+1)+W_(w+1)+W_w",
  "W_W_(w+1)+W_W_(w+1)+W_(w+1)+W",
  "W_W_(w+1)+W_W_(w+1)+W_(w+1)+w",
  "W_W_(w+1)+W_W_(w+1)+W_(w+1)+1",
  "W_W_(w+1)+W_W_(w+1)+W_w+W_w",
  "W_W_(w+1)+W_W_(w+1)+W_w+W",
  "W_W_(w+1)+W_W_(w+1)+W_w+w",
  "W_W_(w+1)+W_W_(w+1)+W_w+1",
  "W_W_(w+1)+W_W_(w+1)+W+W",
  "W_W_(w+1)+W_W_(w+1)+W+w",
  "W_W_(w+1)+W_W_(w+1)+W+1",
  "W_W_(w+1)+W_W_(w+1)+w+w",
  "W_W_(w+1)+W_W_(w+1)+w+1",
  "W_W_(w+1)+W_W_(w+1)+1+1",
  "W_W_(w+1)+W_W+W_W+W_W",
  "W_W_(w+1)+W_W+W_W+W_(w+1)",
  "W_W_(w+1)+W_W+W_W+W_w",
  "W_W_(w+1)+W_W+W_W+W",
  "W_W_(w+1)+W_W+W_W+w",
  "W_W_(w+1)+W_W+W_W+1",
  "W_W_(w+1)+W_W+W_(w+1)+W_(w+1)",
  "W_W_(w+1)+W_W+W_(w+1)+W_w",
  "W_W_(w+1)+W_W+W_(w+1)+W",
  "W_W_(w+1)+W_W+W_(w+1)+w",
  "W_W_(w+1)+W_W+W_(w+1)+1",
  "W_W_(w+1)+W_W+W_w+W_w",
  "W_W_(w+1)+W_W+W_w+W",
  "W_W_(w+1)+W_W+W_w+w",
  "W_W_(w+1)+W_W+W_w+1",
  "W_W_(w+1)+W_W+W+W",
  "W_W_(w+1)+W_W+W+w",
  "W_W_(w+1)+W_W+W+1",
  "W_W_(w+1)+W_W+w+w",
  "W_W_(w+1)+W_W+w+1",
  "W_W_(w+1)+W_W+1+1",
  "W_W_(w+1)+W_(w+1)+W_(w+1)+W_(w+1)",
  "W_W_(w+1)+W_(w+1)+W_(w+1)+W_w",
  "W_W_(w+1)+W_(w+1)+W_(w+1)+W",
  "W_W_(w+1)+W_(w+1)+W_(w+1)+w",
  "W_W_(w+1)+W_(w+1)+W_(w+1)+1",
  "W_W_(w+1)+W_(w+1)+W_w+W_w",
  "W_W_(w+1)+W_(w+1)+W_w+W",
  "W_W_(w+1)+W_(w+1)+W_w+w",
  "W_W_(w+1)+W_(w+1)+W_w+1",
  "W_W_(w+1)+W_(w+1)+W+W",
  "W_W_(w+1)+W_(w+1)+W+w",
  "W_W_(w+1)+W_(w+1)+W+1",
  "W_W_(w+1)+W_(w+1)+w+w",
  "W_W_(w+1)+W_(w+1)+w+1",
  "W_W_(w+1)+W_(w+1)+1+1",
  "W_W_(w+1)+W_w+W_w+W_w",
  "W_W_(w+1)+W_w+W_w+W",
  "W_W_(w+1)+W_w+W_w+w",
  "W_W_(w+1)+W_w+W_w+1",
  "W_W_(w+1)+W_w+W+W",
  "W_W_(w+1)+W_w+W+w",
  "W_W_(w+1)+W_w+W+1",
  "W_W_(w+1)+W_w+w+w",
  "W_W_(w+1)+W_w+w+1",
  "W_W_(w+1)+W_w+1+1",
  "W_W_(w+1)+W+W+W",
  "W_W_(w+1)+W+W+w",
  "W_W_(w+1)+W+W+1",
  "W_W_(w+1)+W+w+w",
  "W_W_(w+1)+W+w+1",
  "W_W_(w+1)+W+1+1",
  "W_W_(w+1)+w+w+w",
  "W_W_(w+1)+w+w+1",
  "W_W_(w+1)+w+1+1",
  "W_W_(w+1)+1+1+1"]

#guard famRwp1.length = 120
#guard famCounts famRwp1 = (300, 45, 402, 75, (6, 108))

end Googology.Trans.BMS.TrioFixNonLastOther2
