import Googology.Trans.DBMS.Blocks
import Googology.Trans.BMS.TrioCofinal

/-!
# The three-row contents are lifted Bashicu matrices

`Blocks.lean` reduces the rank of DBMS with `r + 1` rows to the rank of the
rule of BM4 on the contents `CReach r`, generated by `cgen r n`.  At three rows
the generators are

    cgen 2 (n + 2) = (0,0,0)(1,1,0)(2,2,1)(3,3,2)⋯(n+1,n+1,n)

and this is a zero column followed by the BMS generator
`(0,0,0)(1,1,1)⋯(n,n,n)` with rows `0` and `1` raised by one
(`cgen_two_eq_lift`).  This file names that operation,

    lift r B = (0,…,0) (B₀ with rows 0,1 + 1) (B₁ with rows 0,1 + 1) ⋯

and proves, for every number of rows `r ≥ 2`:

* `ParR_lift_succ`: inside `lift r B` the parents are those of `B`, in every
  row (the zero column in front aside).
* `expandRL_lift`: **expanding `lift r B` is expanding `B`**,
  `(lift r B)[N] = lift r (B[N])`, as long as the last column of `B` has a
  row-`1` parent in `B`, and in every row `k ≥ 2` it has a parent in `B` or
  the entry `0` (`LiftGood`).  The zero column in front is then never the
  bad root, and `m₀` and the bad root are those of `B`.

At three rows this gives the expansions of the content generators:
`(cgen 2 (n + 3))[N] = lift 3 (((0,0,0)(1,1,1)⋯(n+1,n+1,n+1))[N])`
(`expandRL_cgen_two`), and in particular
`(cgen 2 4)[N] = lift 3 (trio generator (0,0,0)(1,1,1)(2,2,1)⋯(N+1,N+1,1))`
(`expandRL_cgen_two_four`).

The condition cannot be dropped.  When the last column of `B` has row-`1`
entry `0`, `lift` gives it the entry `1` and the zero column in front becomes
its row-`1` parent: `B = (0,0,0)` has rank `1`, while
`lift 3 B = (0,0,0)(1,1,0)` has rank `ε₀`.  So the rank of `lift r B` is not
a function of the rank of `B` alone, and this file does not compute it.
-/

namespace Googology.Trans.DBMS

open Googology.Trans.BMS

/-! ### The lift -/

/-- A column with its row-`0` and row-`1` entries raised by one. -/
def up01 (v : List Nat) : List Nat := (v[0]! + 1) :: (v[1]! + 1) :: v.drop 2

/-- A zero column, then `B` with rows `0` and `1` raised by one. -/
def lift (r : Nat) (B : List (List Nat)) : List (List Nat) := zcol r :: B.map up01

/-- `1` in rows `0` and `1`, `0` below. -/
def bump (k : Nat) : Nat := if k < 2 then 1 else 0

@[simp] theorem up01_get0 (v : List Nat) : (up01 v)[0]! = v[0]! + 1 := rfl

@[simp] theorem up01_get1 (v : List Nat) : (up01 v)[1]! = v[1]! + 1 := rfl

theorem up01_get_add2 (v : List Nat) (k : Nat) : (up01 v)[k + 2]! = v[k + 2]! := by
  cases v with
  | nil => rfl
  | cons a t =>
    cases t with
    | nil => rfl
    | cons b t => rfl

theorem up01_get (v : List Nat) (k : Nat) : (up01 v)[k]! = v[k]! + bump k := by
  match k with
  | 0 => rfl
  | 1 => rfl
  | k + 2 => rw [up01_get_add2]; rfl

theorem up01_length {v : List Nat} (h : 2 ≤ v.length) : (up01 v).length = v.length := by
  match v, h with
  | a :: b :: t, _ => simp [up01]

@[simp] theorem lift_length (r : Nat) (B : List (List Nat)) :
    (lift r B).length = B.length + 1 := by simp [lift]

theorem lift_get0 (r : Nat) (B : List (List Nat)) : (lift r B)[0]! = zcol r := rfl

theorem lift_get_succ (r : Nat) (B : List (List Nat)) {i : Nat} (h : i < B.length) :
    (lift r B)[i + 1]! = up01 (B[i]!) := by
  show (B.map up01)[i]! = _
  rw [getElem!_pos _ i (by simpa using h), getElem!_pos B i h, List.getElem_map]

/-! ### Parents inside the lift -/

/-- **Inside the lift the parents are those of `B`**, in every row. -/
theorem ParR_lift_succ (r : Nat) (M : List (List Nat)) :
    ∀ k j i, ParR (lift r M) k (j + 1) (i + 1) ↔ ParR M k j i := by
  intro k
  induction k with
  | zero =>
    intro j i
    by_cases hi : j < i ∧ i < M.length
    · rw [ParR, ParR, lift_get_succ r M hi.2, lift_get_succ r M (by omega), up01_get0, up01_get0]
      constructor
      · rintro ⟨h1, h2, h3⟩
        refine ⟨by omega, by omega, fun j' a b => ?_⟩
        have := h3 (j' + 1) (by omega) (by omega)
        rw [lift_get_succ r M (by omega), up01_get0] at this
        omega
      · rintro ⟨h1, h2, h3⟩
        refine ⟨by omega, by omega, fun j' a b => ?_⟩
        have := h3 (j' - 1) (by omega) (by omega)
        rw [show j' = (j' - 1) + 1 from by omega, lift_get_succ r M (by omega), up01_get0]
        omega
    · constructor
      · intro h
        have h1 := ParR_lt_len h
        have h2 := ParR_lt h
        simp at h1
        exact absurd ⟨by omega, by omega⟩ hi
      · intro h; exact absurd ⟨ParR_lt h, ParR_lt_len h⟩ hi
  | succ m ih =>
    have hTG := transGen_shift (R := ParR (lift r M) m) (R' := ParR M m) ih
      (fun _ _ h => ParR_lt h)
    intro j i
    by_cases hi : j < i ∧ i < M.length
    · rw [ParR, ParR, lift_get_succ r M hi.2, lift_get_succ r M (by omega), up01_get,
        up01_get, hTG]
      constructor
      · rintro ⟨h1, h2, h3, h4⟩
        refine ⟨by omega, h2, by omega, fun j' a b hc => ?_⟩
        have := h4 (j' + 1) (by omega) (by omega) ((hTG j' i).mpr hc)
        rw [lift_get_succ r M (by omega), up01_get] at this
        omega
      · rintro ⟨h1, h2, h3, h4⟩
        refine ⟨by omega, h2, by omega, fun j' a b hc => ?_⟩
        have hj : j' = (j' - 1) + 1 := by omega
        rw [hj] at hc
        rw [hj, lift_get_succ r M (by omega), up01_get]
        have := h4 (j' - 1) (by omega) (by omega) ((hTG _ i).mp hc)
        omega
    · constructor
      · intro h
        have h1 := ParR_lt_len h
        have h2 := ParR_lt h
        simp at h1
        exact absurd ⟨by omega, by omega⟩ hi
      · intro h; exact absurd ⟨ParR_lt h, ParR_lt_len h⟩ hi

theorem AncR_lift_succ (r : Nat) (M : List (List Nat)) (k a b : Nat) :
    AncR (lift r M) k (a + 1) (b + 1) ↔ AncR M k a b :=
  transGen_shift (ParR_lift_succ r M k) (fun _ _ h => ParR_lt h) a b

/-! ### The condition on the last column -/

/-- **The last column of `B` keeps its parents under the lift**: it has a
row-`1` parent, and in every row `k ≥ 2` a parent or the entry `0`. -/
def LiftGood (B : List (List Nat)) : Prop :=
  B ≠ [] ∧ (parAtR B 1 (B.length - 1)).isSome = true ∧
    ∀ k, 2 ≤ k → (parAtR B k (B.length - 1)).isSome = true ∨ (B[B.length - 1]!)[k]! = 0

/-- A row-`(k+1)` parent needs a row-`k` parent. -/
theorem exists_ParR_of_succ {l : List (List Nat)} {k j i : Nat} (h : ParR l (k + 1) j i) :
    ∃ b, ParR l k b i := by
  obtain ⟨b, _, hb⟩ := Relation.TransGen.tail'_iff.mp h.2.1
  exact ⟨b, hb⟩

theorem parAtR_lift_last (r : Nat) {M : List (List Nat)} (hG : LiftGood M) (k : Nat) :
    parAtR (lift r M) k M.length = (parAtR M k (M.length - 1)).map (· + 1) := by
  obtain ⟨hne, h1, h2⟩ := hG
  have hpos : 0 < M.length := List.length_pos_iff.mpr hne
  have hn : M.length = (M.length - 1) + 1 := by omega
  cases h : parAtR M k (M.length - 1) with
  | some p =>
    rw [Option.map_some, parAtR_eq_some, hn, ParR_lift_succ]
    exact (parAtR_eq_some _ _ _ _).mp h
  | none =>
    rw [Option.map_none]
    by_contra hc
    obtain ⟨j, hj⟩ := Option.ne_none_iff_exists'.mp hc
    have hp := (parAtR_eq_some _ _ _ _).mp hj
    cases j with
    | succ j =>
      rw [hn, ParR_lift_succ] at hp
      rw [(parAtR_eq_some _ _ _ _).mpr hp] at h
      exact absurd h (by simp)
    | zero =>
      obtain ⟨q, hq⟩ := Option.isSome_iff_exists.mp h1
      have hq' := (parAtR_eq_some _ _ _ _).mp hq
      match k with
      | 0 =>
        obtain ⟨b, hb⟩ := exists_ParR_of_succ hq'
        rw [(parAtR_eq_some _ _ _ _).mpr hb] at h
        exact absurd h (by simp)
      | 1 =>
        rw [hq] at h
        exact absurd h (by simp)
      | k + 2 =>
        rcases h2 (k + 2) (by omega) with hs | hz
        · rw [h] at hs; exact absurd hs (by simp)
        · have hv := hp.2.2.1
          rw [lift_get0, zcol_get, hn, lift_get_succ r M (by omega), up01_get_add2, hz] at hv
          exact absurd hv (by omega)

theorem m0L_lift (r : Nat) {M : List (List Nat)} (hG : LiftGood M) :
    m0L r (lift r M) = m0L r M := by
  rw [m0L, m0L, lift_length, Nat.add_sub_cancel]
  exact findGreatest_congr (r - 1) (fun k _ => by
    rw [parAtR_lift_last r hG k, Option.isSome_map])

theorem badRootR_lift (r : Nat) {M : List (List Nat)} (hG : LiftGood M) :
    badRootR r (lift r M) = (badRootR r M).map (· + 1) := by
  have hne' : ¬ (lift r M).isEmpty = true := by simp [lift]
  have hneM : ¬ M.isEmpty = true := by simpa [List.isEmpty_iff] using hG.1
  rw [badRootR, badRootR, if_neg hne', if_neg hneM, lift_length, Nat.add_sub_cancel,
    m0L_lift r hG]
  exact parAtR_lift_last r hG _

/-! ### Expanding the lift -/

theorem lift_dropLast (r : Nat) {M : List (List Nat)} (hne : M ≠ []) :
    lift r M.dropLast = (lift r M).dropLast := by
  rw [lift, lift, List.dropLast_cons_of_ne_nil (by simpa using hne), List.map_dropLast]

theorem lift_append (r : Nat) (A B : List (List Nat)) :
    lift r (A ++ B) = lift r A ++ B.map up01 := by
  simp [lift]

theorem lift_map_range (r : Nat) (M : List (List Nat)) {p : Nat} (hp : p ≤ M.length) :
    lift r ((List.range p).map (fun i => M[i]!))
      = (List.range (p + 1)).map (fun i => (lift r M)[i]!) := by
  rw [List.range_succ_eq_map, List.map_cons, List.map_map, lift, List.map_map]
  congr 1
  refine List.map_congr_left (fun i hi => ?_)
  have hi' : i < p := List.mem_range.mp hi
  exact (lift_get_succ r M (by omega)).symm

theorem up01_map_range (r' : Nat) (f g : Nat → Nat) (h0 : g 0 = f 0 + 1)
    (h1 : g 1 = f 1 + 1) (hs : ∀ k, g (k + 2) = f (k + 2)) :
    (List.range (r' + 2)).map g = up01 ((List.range (r' + 2)).map f) := by
  rw [List.range_succ_eq_map, List.range_succ_eq_map]
  simp only [List.map_cons, List.map_map, up01, List.drop_succ_cons, List.drop_zero]
  refine congrArg₂ _ (by rw [h0]; rfl) (congrArg₂ _ (by rw [h1]; rfl) ?_)
  exact List.map_congr_left (fun k _ => hs k)

/-- **Expanding the lift is expanding `B`**, when the last column of `B` keeps
its parents. -/
theorem expandRL_lift (r N : Nat) (hr : 2 ≤ r) {M : List (List Nat)} (hG : LiftGood M) :
    expandRL r N (lift r M) = lift r (expandRL r N M) := by
  have hne := hG.1
  have hpos : 0 < M.length := List.length_pos_iff.mpr hne
  cases hb : badRootR r M with
  | none =>
    rw [expandRL, badRootR_lift r hG, hb, Option.map_none]
    conv_rhs => rw [expandRL, hb]
    exact (lift_dropLast r hne).symm
  | some p =>
    have hp : p + 1 < M.length := badRootR_lt hb
    rw [expandRL, badRootR_lift r hG, hb, Option.map_some]
    conv_rhs => rw [expandRL, hb]
    dsimp only
    rw [lift_append, lift_map_range r M (by omega), List.map_map]
    congr 1
    rw [lift_length, Nat.add_sub_cancel, show M.length - (p + 1) = M.length - 1 - p from by omega,
      m0L_lift r hG]
    refine List.map_congr_left (fun t _ => ?_)
    obtain ⟨r', rfl⟩ : ∃ r', r = r' + 2 := ⟨r - 2, by omega⟩
    have hs : 0 < M.length - 1 - p := by omega
    have hx : p + t % (M.length - 1 - p) < M.length := by
      have := Nat.mod_lt t hs; omega
    have e1 : (lift (r' + 2) M)[p + 1 + t % (M.length - 1 - p)]!
        = up01 (M[p + t % (M.length - 1 - p)]!) := by
      rw [show p + 1 + t % (M.length - 1 - p) = (p + t % (M.length - 1 - p)) + 1 from by omega]
      exact lift_get_succ _ M hx
    have e2 : (lift (r' + 2) M)[p + 1]! = up01 (M[p]!) := lift_get_succ _ M (by omega)
    have e3 : (lift (r' + 2) M)[M.length]! = up01 (M[M.length - 1]!) := by
      conv_lhs => rw [show M.length = (M.length - 1) + 1 from by omega]
      exact lift_get_succ _ M (by omega)
    have e4 : ∀ k, ancAtR (lift (r' + 2) M) k (p + 1) (p + 1 + t % (M.length - 1 - p))
        = ancAtR M k p (p + t % (M.length - 1 - p)) := by
      intro k
      rw [Bool.eq_iff_iff, ancAtR_iff, ancAtR_iff,
        show p + 1 + t % (M.length - 1 - p) = (p + t % (M.length - 1 - p)) + 1 from by omega]
      exact AncR_lift_succ _ M k p _
    have e5 : (p + 1 == p + 1 + t % (M.length - 1 - p)) = (p == p + t % (M.length - 1 - p)) := by
      rw [Bool.eq_iff_iff, beq_iff_eq, beq_iff_eq]; omega
    simp only [Function.comp, e1, e2, e3, e4, e5]
    refine up01_map_range r' _ _ ?_ ?_ ?_
    · simp only [up01_get0]
      split
      · rw [Nat.add_sub_add_right]; ring
      · rfl
    · simp only [up01_get1]
      split
      · rw [Nat.add_sub_add_right]; ring
      · rfl
    · intro k
      simp only [up01_get_add2]

/-! ### Three rows: the content generators -/

/-- The BMS generator `(0,0,0)(1,1,1)⋯(n,n,n)` with three rows. -/
def bgen3 (n : Nat) : List (List Nat) := (List.range (n + 1)).map (fun i => List.replicate 3 i)

/-- **The content generator is the lifted BMS generator.** -/
theorem cgen_two_eq_lift (n : Nat) : cgen 2 (n + 2) = lift 3 (bgen3 n) := by
  rw [cgen, List.range_succ_eq_map (n := n + 1), List.map_cons, lift, bgen3, List.map_map,
    List.map_map]
  congr 1

/-- Adjacent columns that increase in every row up to `k` are parents. -/
theorem ParR_pred_of_lt (l : List (List Nat)) (i : Nat) (hi : 0 < i) :
    ∀ k, (∀ k', k' ≤ k → (l[i - 1]!)[k']! < (l[i]!)[k']!) → ParR l k (i - 1) i := by
  intro k
  induction k with
  | zero =>
    intro h
    exact ⟨by omega, h 0 (le_refl _), fun j' a b => absurd b (by omega)⟩
  | succ m ih =>
    intro h
    exact ⟨by omega, Relation.TransGen.single (ih (fun k' hk => h k' (by omega))),
      h (m + 1) (le_refl _), fun j' a b => absurd b (by omega)⟩

theorem bgen3_get {n i : Nat} (hi : i < n + 1) : (bgen3 n)[i]! = List.replicate 3 i := by
  rw [bgen3, getElem!_map_range _ _ hi]

theorem liftGood_bgen3 (n : Nat) : LiftGood (bgen3 (n + 1)) := by
  have hlen : (bgen3 (n + 1)).length = n + 2 := by simp [bgen3]
  have hlt : ∀ k', k' ≤ 2 → ((bgen3 (n + 1))[(n + 2) - 1 - 1]!)[k']!
      < ((bgen3 (n + 1))[(n + 2) - 1]!)[k']! := by
    intro k' hk
    rw [bgen3_get (by omega), bgen3_get (by omega)]
    match k', hk with
    | 0, _ => simp
    | 1, _ => simp
    | 2, _ => simp
  have hpar : ∀ k, k ≤ 2 → (parAtR (bgen3 (n + 1)) k ((n + 2) - 1)).isSome = true := by
    intro k hk
    exact Option.isSome_iff_exists.mpr ⟨_, (parAtR_eq_some _ _ _ _).mpr
      (ParR_pred_of_lt _ _ (by omega) k (fun k' hk' => hlt k' (by omega)))⟩
  refine ⟨by simp [bgen3], by rw [hlen]; exact hpar 1 (by omega), fun k hk => ?_⟩
  rw [hlen]
  by_cases h2 : k = 2
  · exact Or.inl (h2 ▸ hpar 2 (le_refl _))
  · refine Or.inr ?_
    rw [bgen3_get (by omega)]
    exact getElem!_neg _ k (by simp; omega)

/-- **The content generators expand as the lifted BMS generators.** -/
theorem expandRL_cgen_two (n N : Nat) :
    expandRL 3 N (cgen 2 (n + 3)) = lift 3 (expandRL 3 N (bgen3 (n + 1))) := by
  rw [cgen_two_eq_lift]
  exact expandRL_lift 3 N (by norm_num) (liftGood_bgen3 n)

/-- **The first case beyond `rkL_cgen_three`**: `(0,0,0)(1,1,0)(2,2,1)(3,3,2)`
expands to the lifted trio generators,
`(cgen 2 4)[N] = (0,0,0)(1,1,0)(2,2,1)(3,3,1)⋯(N+2,N+2,1)
= lift 3 ((0,0,0)(1,1,1)(2,2,1)⋯(N+1,N+1,1))`. -/
theorem expandRL_cgen_two_four (N : Nat) :
    expandRL 3 N (cgen 2 4) = lift 3 (TrioCofinal.trioGen (N + 1)) := by
  rw [expandRL_cgen_two 1 N]
  exact congrArg (lift 3) (TrioCofinal.expandRL_stair2 N)

/-! ### The rank, through the lift -/

open Ordinal Order

/-- The rank of the content generator `cgen 2 (n + 3)` is the supremum over
the lifted expansions of the BMS generator `(0,0,0)(1,1,1)⋯(n+1,n+1,n+1)`. -/
theorem rkL_cgen_two_eq_iSup (n : Nat) :
    rkL 2 (cgen 2 (n + 3))
      = ⨆ N : Nat, succ (rkL 2 (lift 3 (expandRL 3 N (bgen3 (n + 1))))) := by
  rw [rkL_step (valid_cgen 2 (n + 3)) (by simp [cgen])]
  exact congrArg _ (funext fun N => congrArg (fun x => succ (rkL 2 x)) (expandRL_cgen_two n N))

end Googology.Trans.DBMS
